// Code generated by tygo. DO NOT EDIT.

//////////
// source: dto.go
/*
Package apidto is sakms's curated, exported request/response DTO
boundary for the future frontend's generated TypeScript API client (see
.omc/plans/frontend-redesign-seerr.md, Stage 0 / Guardrail #4).

Why this package exists: today's handlers decode/encode JSON using
unexported request structs (e.g. internal/api's upsertConnectionRequest)
and raw internal/domain structs (e.g. tmdb.Item, connections.Summary)
encoded directly. A source-parsing codegen tool CAN see unexported types
if pointed at internal/api directly, but that would emit a TypeScript
type for every internal handler struct across the whole package — far
more than a frontend client should ever import, and it would silently
change shape every time an unrelated handler's internal request struct
changed. This package is the deliberate alternative: a small, hand-picked,
EXPORTED set of types that mirror only what a frontend actually needs to
send/receive, kept in one place a codegen tool can be pointed at in
isolation (see internal/apidto/gen).

Scope (Stage 0 / Stage 1 only — see README.md "Scope grows per stage"):
auth boot (setup/login/status/mode/OIDC config/API key management) and
Discover's read-only surface (poster items + availability badges), the
exact set Stage 1's toolchain slice consumes. Stages 2-4 add their own
DTOs here as their frontend work lands — this file is a starting point,
not a final inventory, per Guardrail #4.

These types are currently PARALLEL COPIES of the shapes already produced
by internal/api's handlers (authStatusResponse, oidcStatusResponse,
tmdb.Item, etc.) and internal/auth's APIKeyStatus. Stage 0 defines them
but does not wire any handler to use them — no frontend exists yet to
prove a wiring change against, and touching the auth handlers here would
add lockout risk for zero benefit (see README.md). Stage 1 is expected to
converge the real handlers onto these exact types, at which point the
parallel definitions in internal/api collapse into a single source of
truth here.

Field names, JSON tags, and types below match the current wire format
exactly (same lowerCamelCase JSON keys the existing handlers already
emit) so that a future Stage-1 handler swap is a type substitution, not a
wire-format change.

IMPORTANT — three-state optional-secret fields (Guardrail #5): see
ConnectionUpsertRequest.APIKey's doc comment and README.md's "Three-state
secret mapping rule" section before generating or consuming a TypeScript
client for any *string field in this package.
*/

/**
 * SetupRequest is the body of POST /api/auth/setup — SAK's one-time,
 * first-run login bootstrap. Mode selects the auth strategy ("password" is
 * the default when Mode is omitted, "oidc", or "none").
 * AcknowledgeInsecure must be true to select Mode "none". The four
 * OIDC* fields are required together, and only meaningful, when
 * Mode == "oidc".
 */
export interface SetupRequest {
  username: string;
  password: string;
  mode: string;
  acknowledgeInsecure: boolean;
  oidcIssuerUrl?: string;
  oidcClientId?: string;
  oidcClientSecret?: string;
  oidcRedirectUrl?: string;
}
/**
 * SetupResponse is returned by POST /api/auth/setup only for "oidc"-mode
 * setup (empty body / 204 for "password"/"none"). Exactly one of APIKey or
 * APIKeyNote is populated: APIKey is a one-time break-glass credential
 * revealed ONCE, never retrievable again; APIKeyNote is present instead
 * when SAKMS_API_KEY is set via environment (no settings-managed key is
 * minted in that case — the env value IS the break-glass credential).
 */
export interface SetupResponse {
  apiKey?: string;
  apiKeyNote?: string;
}
/**
 * LoginRequest is the body of POST /api/auth/login — only meaningful when
 * the active auth mode is "password" (checked server-side; "oidc" logs in
 * via a full-page redirect to /api/auth/oidc/login instead, and "none" has
 * no login step).
 */
export interface LoginRequest {
  username: string;
  password: string;
}
/**
 * AuthStatusResponse is GET /api/auth/status's response — the one call the
 * frontend's boot sequence makes before it knows anything else about the
 * instance, deciding between the setup wizard, the login screen, and the
 * app (see Guardrail #2's 3-way boot branch). Mode is one of "password",
 * "oidc", or "none".
 */
export interface AuthStatusResponse {
  configured: boolean;
  authenticated: boolean;
  mode: string;
}
/**
 * AuthModeResponse is GET /api/auth/mode's response.
 */
export interface AuthModeResponse {
  mode: string;
}
/**
 * AuthModeRequest is PUT /api/auth/mode's body — switches the ALREADY
 * authenticated operator's active auth mode. AcknowledgeInsecure must be
 * true to switch into "none" (mirrors SetupRequest's same field for the
 * first-run case).
 */
export interface AuthModeRequest {
  mode: string;
  acknowledgeInsecure: boolean;
}
/**
 * OIDCStatusResponse is GET /api/auth/oidc's response. HasSecret reports
 * whether a client secret is currently stored; the secret itself is NEVER
 * returned (mirrors ConnectionSummary's HasAPIKey/KeySuffix pattern for the
 * same reason — see README.md).
 */
export interface OIDCStatusResponse {
  issuerUrl: string;
  clientId: string;
  redirectUrl: string;
  hasSecret: boolean;
}
/**
 * OIDCConfigRequest is PUT /api/auth/oidc's body — sets/replaces the
 * OIDC provider config for an already-configured instance. Unlike
 * ConnectionUpsertRequest.APIKey, ClientSecret here is a plain (non-pointer)
 * required field: every PUT to this endpoint must supply the full config,
 * there is no "leave secret unchanged" partial-update mode for OIDC config
 * today.
 */
export interface OIDCConfigRequest {
  issuerUrl: string;
  clientId: string;
  clientSecret: string;
  redirectUrl: string;
}
/**
 * APIKeyStatusResponse is GET /api/apikey's response. Source is one of
 * "env" (SAKMS_API_KEY active), "settings" (a regenerated key is stored),
 * or "none" (no key exists). The key itself is never returned here — only
 * KeySuffix, matching ConnectionSummary's masked-display convention.
 */
export interface APIKeyStatusResponse {
  hasKey: boolean;
  keySuffix?: string;
  source: string;
}
/**
 * APIKeyRegenerateResponse is POST /api/apikey/regenerate's response — the
 * one place the full API key crosses the API boundary. Shown once, never
 * retrievable again afterward (same one-shot-reveal contract as
 * SetupResponse.APIKey).
 */
export interface APIKeyRegenerateResponse {
  apiKey: string;
  keySuffix: string;
}
/**
 * ModeStatus reports what's configured for one mode (Mode is one of
 * "movies", "series", "adult") — enough for the setup wizard to know which
 * steps are already done and skip past them.
 */
export interface ModeStatus {
  mode: string;
  available: boolean;
  arrConfigured: boolean;
  allowlistCount: number /* int */;
}
/**
 * SetupStatusResponse is GET /api/setup/status's response — a pure read
 * model over what's already configured, driving whether the setup wizard
 * shows itself at all and which of its steps it can skip.
 */
export interface SetupStatusResponse {
  modes: ModeStatus[];
  jellyfinConfigured: boolean;
  ollamaConfigured: boolean;
  dismissed: boolean;
  anyConfigured: boolean;
}
/**
 * DismissSetupRequest is PUT /api/setup/dismissed's body.
 */
export interface DismissSetupRequest {
  dismissed: boolean;
}
/**
 * DiscoverItem is one TMDB trending/popular result for Movies/Series
 * Discover (GET /api/modes/{mode}/discover) — mirrors tmdb.Item's exact
 * wire shape. MediaType is "movie" or "tv".
 */
export interface DiscoverItem {
  id: number /* int */;
  title: string;
  posterPath: string;
  overview: string;
  releaseDate: string;
  voteAverage: number /* float64 */;
  mediaType: string;
}
/**
 * AdultDiscoverItem is one TPDB scene result for Adult Discover
 * (GET /api/modes/adult/discover) — scene-shaped, not title-shaped (Studio
 * substitutes for a studio/site name). Date is TPDB's release date string,
 * unparsed. Image is the scene thumbnail URL served from TPDB's own image CDN
 * (cdn.theporndb.net); it is frequently empty (many scenes have no art), so
 * the client must render a text-only card when blank and route non-empty
 * values through the image proxy (GET /api/images/proxy?url=), never
 * hot-linking TPDB directly (plan Decision #7). DurationSeconds is the
 * scene's pre-grab runtime in seconds (see internal/tpdbrest.Scene.Duration
 * for sourcing/confidence: documented-shape + corroborated by two
 * independent sources, not live-confirmed against a real TPDB instance); it
 * may be 0 (unknown), which the auto-grab bitrate scorer (Stage 2) must
 * treat as "skip the pre-grab bitrate check," never a real zero-length
 * runtime or a divide-by-zero input.
 * Rating is the scene's own numeric rating (TPDB's "rating" field; the spec's
 * example value is the integer 5). It backs Adult Discover's "Highest Rated"
 * row, which the backend produces by re-sorting ONE browse page by this field
 * descending — a page-local ordering, NOT a true global popularity ranking (see
 * internal/tpdbrest.BrowseScenes' doc). May be 0 (absent/unrated).
 * Source names which upstream catalog the scene came from: "tpdb", "stashdb",
 * or "fansdb". TPDB's own rows and the merged "Recently Released" feed set it
 * so the card can show a provenance label; stash-box has no numeric rating, so
 * a "stashdb"/"fansdb" scene's Rating is always 0.
 * Slug is TPDB's URL-friendly scene identifier, used by the Discover detail
 * popup's "More on TPDB" external link (theporndb.net/scenes/{slug}, NOT
 * {id} — see internal/tpdbrest.Scene.Slug for sourcing). Always empty for a
 * "stashdb"/"fansdb" scene: those sites' own detail pages are UUID-path
 * (stashdb.org/scenes/{id}), so the popup links via ID for them instead.
 * ReleaseTitle is only populated for a scene sourced from the newest-rows
 * pipeline (see AdultNewestReleaseItem.ReleaseTitle) — the popup/Grab dialog
 * thread it through as AutoGrabRequest.ReleaseTitle when present. Always ""
 * for a plain TPDB/StashDB/FansDB catalog browse item (no associated
 * Prowlarr release to remember), which falls back to the Studio+Title
 * query, same as before this field existed.
 * Genres/Performers back the Discover detail popup's tags/performers list.
 * Populated for TPDB-sourced items (catalog browse and newest-rows alike —
 * see internal/tpdbrest.Scene.Tags/Performers and
 * adultnewest.MatchedRelease.Genres/Performers for sourcing); empty for a
 * StashDB/FansDB item (that schema's shape hasn't been verified against a
 * live instance yet — see CLAUDE.md's "honesty about unverified
 * assumptions"). Both omitempty since most callers (any pre-existing cached
 * entity, any stash-box item) legitimately have neither.
 */
export interface AdultDiscoverItem {
  id: string;
  title: string;
  studio: string;
  date: string;
  image: string;
  durationSeconds: number /* int */;
  rating: number /* float64 */;
  source: string;
  slug: string;
  releaseTitle?: string;
  genres?: string[];
  performers?: string[];
}
/**
 * StudioSummary is one entry in Adult Discover's Studios row
 * (GET /api/modes/adult/studios) — a TPDB site (studio) reduced to just what a
 * browse card and its drill-down link need. ID is the opaque TPDB site id (used
 * as the {id} path segment of GET /api/modes/adult/studios/{id}/scenes). Image
 * is a single chosen studio image URL (first non-empty of TPDB's logo/poster/
 * favicon), frequently empty (no art) — render a text-only card when blank and
 * route non-empty values through the image proxy, never hot-link TPDB directly.
 */
export interface StudioSummary {
  id: string;
  name: string;
  image: string;
  source: string;
}
/**
 * PerformerSummary is one entry in Adult Discover's Performers row
 * (GET /api/modes/adult/performers) — a TPDB performer reduced to browse-card
 * fields. ID is the opaque TPDB performer id (the {id} path segment of
 * GET /api/modes/adult/performers/{id}/scenes). Image is a single chosen
 * performer image URL (first non-empty of TPDB's image/thumbnail/face),
 * frequently empty — same text-fallback + image-proxy rule as StudioSummary.
 */
export interface PerformerSummary {
  id: string;
  name: string;
  image: string;
  source: string;
}
/**
 * PosterResponse is GET /api/modes/{mode}/poster's response — the lazily
 * resolved TMDB poster path for one library card, keyed by tmdbId (Movies/
 * Series only). PosterPath is a bare TMDB path (e.g. "/abc.jpg") the client
 * turns into a proxied image URL, or "" when TMDB has no art on file (the
 * card then renders its text fallback). Mirrors the availability probe's
 * per-card, on-demand shape rather than an N+1 on the library list endpoint.
 */
export interface PosterResponse {
  posterPath: string;
}
/**
 * AvailabilityResponse is GET /api/modes/{mode}/availability's response —
 * backs a Discover card's availability badge (Stage 1 scope: "poster cards
 * with availability badges" per the plan). CheckedAt is an RFC3339Nano
 * timestamp of when the probe ran.
 */
export interface AvailabilityResponse {
  available: boolean;
  releaseCount: number /* int */;
  checkedAt: string;
}
/**
 * ConnectionSummary is one entry of GET /api/connections's response — what's
 * safe to expose about a configured connection: never the secret itself,
 * only whether one is set and its last 4 characters (masked display).
 * Included here alongside ConnectionUpsertRequest even though the
 * Connections/Settings UI itself isn't built until Stage 4 — see
 * ConnectionUpsertRequest's doc comment for why.
 */
export interface ConnectionSummary {
  service: string;
  url: string;
  username?: string;
  hasApiKey: boolean;
  keySuffix?: string;
  updatedAt: string;
}
/**
 * ConnectionUpsertRequest is PUT /api/connections/{service}'s body —
 * included in Stage 0's curated set (ahead of Stage 4, when Settings'
 * actual frontend lands) specifically BECAUSE it carries the single most
 * safety-critical mapping rule in this whole DTO boundary (Guardrail #5)
 * and needed to be proven against the chosen codegen tool before that tool
 * choice was finalized, not discovered as a surprise in Stage 4.
 * APIKey is a pointer so the three states a client MUST be able to express
 * survive the JSON round-trip (json.Decode sets it accordingly; omitempty
 * only affects marshaling, never decoding):
 *   - field ABSENT from the request body entirely (nil)  → preserve the
 *     stored secret. The server never sends the real secret back to a
 *     client (see ConnectionSummary above — only HasAPIKey/KeySuffix are
 *     exposed), so an untouched, blank key input MUST be omitted from the
 *     JSON body, never sent as "".
 *   - field present as ""  (&"")                          → explicitly
 *     clear the stored secret (e.g. switching to a service that needs
 *     none, like Ollama).
 *   - field present, non-empty  (&"sk-...")                → set/replace
 *     the stored secret.
 * TypeScript CANNOT express this three-way distinction as a type — both
 * a field absent entirely and a field present with an empty-string value
 * collapse to the same `string | undefined` a source-parsing generator
 * emits for a Go *string.
 * See README.md's "Three-state secret mapping rule" section for the
 * generated TypeScript shape and the load-bearing prose rule a frontend
 * MUST follow by convention (not by the type system) when building this
 * request body.
 */
export interface ConnectionUpsertRequest {
  url: string;
  username?: string;
  apiKey?: string;
}
/**
 * Grab mirrors internal/grabs.Grab's exact wire shape — the record SAK keeps
 * for one release it has sent to a download client. Exposed here so the
 * frontend's Grabs view and the auto-grab response share one generated
 * TypeScript type instead of hand-duplicating the shape.
 * FlaggedForReview / FlagReason are the ADVISORY post-grab mislabel signal
 * (set by checkImportHandler via internal/autograb.RuntimeMismatch, Movies
 * only for now): they do NOT mean the import failed — the import already
 * succeeded — only that the imported file's runtime looked inconsistent with
 * its metadata and a human might want to eyeball it. The Grabs view must say
 * so in its copy, never present the flag as an error.
 */
export interface Grab {
  id: number /* int64 */;
  mode: string;
  title: string;
  tmdbId?: number /* int */;
  tvdbId?: number /* int */;
  seasonNumber?: number /* int */;
  episodeNumber?: number /* int */;
  seasonSpecified?: boolean;
  qualityProfileId?: number /* int */;
  indexer: string;
  protocol: string;
  downloadClient: string;
  clientRef?: string;
  status: string;
  rootFolderPath: string;
  flaggedForReview?: boolean;
  flagReason?: string;
  createdAt: string;
  updatedAt: string;
}
/**
 * AutoGrabRequest is POST /api/modes/{mode}/autograb's body — Discover's
 * one-click unattended grab trigger for exactly one title/scene. Which fields
 * matter is mode-specific:
 *   - Movies:  TMDBID (drives the id-scoped Prowlarr search AND the TMDB
 *     runtime lookup the bitrate scorer needs) + Title.
 *   - Series:  TMDBID + Title + SeasonNumber/EpisodeNumber/SeasonSpecified —
 *     the picker's selection ("one click PER season/episode selection", per
 *     the plan's per-mode nuance). No per-episode runtime exists pre-grab
 *     today, so Series candidates all grade as unknown-bitrate and the call
 *     returns the manual fallback list rather than auto-grabbing (documented
 *     behavior, not a bug). SeasonSpecified must be threaded through so a
 *     deliberate Season-0/Specials grab isn't misread as "no season picked"
 *     (see grabs.Grab.SeasonSpecified / checkImportHandler).
 *   - Adult:   Title + Studio (the free-text Prowlarr query fallback) +
 *     ReleaseTitle (preferred query when present — the raw Prowlarr release
 *     title that first matched this entity, see
 *     adultnewest.MatchedRelease.FirstSeenReleaseTitle's doc comment for why
 *     it's more reliable than reconstructing a query from Title/Studio) +
 *     DurationSeconds (TPDB's pre-grab runtime → the scorer's
 *     RuntimeSeconds; 0 = unknown, handled neutrally).
 */
export interface AutoGrabRequest {
  title: string;
  tmdbId?: number /* int */;
  studio?: string;
  seasonNumber?: number /* int */;
  episodeNumber?: number /* int */;
  seasonSpecified?: boolean;
  durationSeconds?: number /* int */;
  /**
   * ReleaseTitle is Adult-only — see this struct's doc comment above.
   */
  releaseTitle?: string;
}
/**
 * AutoGrabCandidate is one graded release in an auto-grab manual-fallback list
 * (AutoGrabResponse.Candidates). It pairs the grade (Status = why it did/didn't
 * auto-qualify, Score = the bitrate ranking key) with the exact release
 * identity the frontend needs to grab it manually via
 * POST /api/modes/{mode}/search/grab — one release per click, never a batch.
 * Status is one of internal/autograb.Status's values ("qualified",
 * "below-floor", "mislabeled", "low-seeders", "unknown-bitrate",
 * "unknown-resolution").
 */
export interface AutoGrabCandidate {
  title: string;
  indexer: string;
  protocol: string;
  downloadUrl: string;
  size: number /* int64 */;
  seeders: number /* int */;
  status: string;
  score: number /* float64 */;
  impliedMbps: number /* float64 */;
  floorMbps: number /* float64 */;
  qualified: boolean;
}
/**
 * AutoGrabResponse is POST /api/modes/{mode}/autograb's result — exactly one
 * of two outcomes:
 *   - Grabbed == true:  a release cleared every gate and was sent to the
 *     download client. Grab is the recorded grab (also visible in the Grabs
 *     view); Candidates is empty.
 *   - Grabbed == false (Fallback == true): nothing auto-qualified —
 *     Candidates is the ranked manual pick list (best bitrate score first,
 *     the SAME score that gated auto-grab), each row labeled with why it
 *     didn't qualify. The operator picks exactly one to grab; Grab is nil.
 * Message is a short human summary for the UI.
 */
export interface AutoGrabResponse {
  grabbed: boolean;
  fallback: boolean;
  message: string;
  grab?: Grab;
  candidates?: AutoGrabCandidate[];
}
/**
 * AvailabilityPreview is the full 4-resolution grid — one upfront fetch backs
 * every selector combination the popup's UI offers, so switching any
 * selector re-renders instantly against already-fetched data (no refetch per
 * selection change).
 */
export interface AvailabilityPreview {
  res2160: ResolutionAvailability;
  res1080: ResolutionAvailability;
  res720: ResolutionAvailability;
  res480: ResolutionAvailability;
}
/**
 * ResolutionAvailability is one resolution bucket's 4-tier grid.
 */
export interface ResolutionAvailability {
  low: TierAvailability;
  medium: TierAvailability;
  high: TierAvailability;
  lossless: TierAvailability;
}
/**
 * TierAvailability is one (resolution, tier) cell's 2-protocol leaf. Usenet/
 * Torrent are nil when autograb.Select found no qualifying candidate for that
 * exact (resolution, tier, protocol) combination — the popup's selector
 * greys out that option.
 */
export interface TierAvailability {
  usenet?: AvailabilityCandidate;
  torrent?: AvailabilityCandidate;
}
/**
 * AvailabilityCandidate is the winning release for one (resolution, tier,
 * protocol) combination — everything the popup's Grab button needs to call
 * the EXISTING POST /api/modes/{mode}/search/grab (no new grab endpoint; see
 * the plan's "Grab" section). Score is autograb.Grade.Score (the
 * bitrate-based ranking key), deliberately NOT release.ScoreCandidate — the
 * same distinct scorer auto-grab already uses for tier-floor gating.
 */
export interface AvailabilityCandidate {
  guid: string;
  title: string;
  indexer: string;
  protocol: string;
  size: number /* int64 */;
  seeders: number /* int */;
  downloadUrl: string;
  publishDate: string;
  score: number /* float64 */;
}
/**
 * Candidate is one file in a Dedup proposal's duplicate group — the shape the
 * Dedup view (frontend/src/screens/Dedup.tsx) renders one table row from. A
 * CURATED subset of internal/proposals.Candidate: only the fields the view
 * actually displays (Label/Path/Resolution/Codec/BitRate) plus Winner, the
 * keeper-vs-duplicate flag. Winner==true is the "tracked copy" the group keeps;
 * every other candidate is a duplicate the Apply removes (see
 * internal/dedup.ApplyLibrary*). Wire order is load-bearing: DedupApplyRequest's
 * KeepIndex is an ARRAY INDEX into this exact slice (proposals.Proposal.Candidates
 * order), so the client MUST render candidates in received order and never sort
 * them, or the index it sends resolves to the wrong file. proposals.Candidate's
 * TrackedID/PHash are intentionally omitted — the view reads neither, and this
 * package curates to what the frontend consumes (see the Proposal doc / package doc).
 */
export interface Candidate {
  label: string;
  path: string;
  resolution: number /* int */;
  codec: string;
  bitRate: number /* int64 */;
  winner: boolean;
}
/**
 * Proposal is one staged review-queue row as the Rename/Purge/Dedup views consume
 * it. SourceName/RootFolderPath/Reason are always present; Title/Year are only
 * meaningful once Status is pending/applied; Reason explains an unmatched row;
 * DraftID is set once a successful submit-draft ("give back") has run, so the
 * button renders as already-done and can't re-submit. Studio/Date/PHash are
 * Adult-only (captured from Adult identification); SeasonNumber/EpisodeNumber
 * are Series-only (a season-pack orphan produces one proposal per episode).
 * Candidates is Dedup-only: the duplicate group's files, exactly one flagged
 * Winner (the keeper); Rename/Purge never populate it (it's absent from their
 * wire rows, so the shared TS type carries it as optional).
 */
export interface Proposal {
  id: number /* int64 */;
  status: string;
  sourceName: string;
  rootFolderPath: string;
  title?: string;
  year?: number /* int */;
  seasonNumber?: number /* int */;
  episodeNumber?: number /* int */;
  studio?: string;
  date?: string;
  phash?: string;
  reason?: string;
  draftId?: string;
  candidates?: Candidate[];
}
/**
 * AllowlistAddRequest is the body of POST /api/modes/{mode}/purge/allowlist —
 * adds one tag rule to a mode's Purge allowlist. Mirrors internal/api's
 * unexported addAllowlistTagRequest exactly. Adding a tag already present is
 * not an error (see allowlist.Store.Add).
 */
export interface AllowlistAddRequest {
  tag: string;
}
/**
 * RepickRequest is the body of POST /api/proposals/{id}/repick — Rename's
 * manual-override path when Scan's automatic TMDB match was wrong or scored too
 * low to auto-accept (Movies/Series only; Adult identifies via a different id
 * space with its own give-back correction). TMDBID and Title are both required
 * and carry the NEWLY chosen match from the tmdb-search result, never the
 * proposal's current tmdbId; Year is optional (parsed from the result's
 * release date when present). Mirrors internal/api's repickProposalRequest.
 */
export interface RepickRequest {
  tmdbId: number /* int */;
  title: string;
  year?: number /* int */;
}
/**
 * DedupApplyRequest is the OPTIONAL body of POST /api/proposals/{id}/apply when
 * the proposal is a Dedup group (Rename/Purge send an empty body and ignore
 * these fields — see internal/api's applyProposalRequest, which this mirrors).
 * Exactly one of two shapes is sent per Apply:
 *   - {keepIndex: N} — keep candidate N, delete every other candidate in the
 *     group. N is an ARRAY INDEX into Proposal.Candidates in received order
 *     (the radio the operator selected; the group's Winner is pre-selected).
 *     KeepIndex MUST be sent even when it is 0 — a falsy-guard that drops a
 *     literal 0 makes the backend fall back to its own auto-winner and can
 *     delete the file the operator actually chose to keep (dedup.ApplyLibrary
 *     indexes p.Candidates[keepIndex] directly).
 *   - {keepAll: true} — keep every candidate, delete nothing ("Keep All"). The
 *     conservative escape hatch when the group isn't really a duplicate.
 * KeepIndex is a pointer/omitempty so "keep all" omits it entirely rather than
 * sending 0 (which would mean "keep candidate 0").
 */
export interface DedupApplyRequest {
  keepIndex?: number /* int */;
  keepAll?: boolean;
}
/**
 * TagEntry is one entry in a mode's tag vocabulary — mirrors internal/api's
 * libraryTagEntry. A local tag has no numeric id, so ID and Label are the same
 * string value; ID exists only to keep the {id, label} shape the frontend's
 * datalist/lookup logic expects. Returned by both the Movies/Series generic
 * vocab route and Adult's dedicated scene-tag vocab route.
 */
export interface TagEntry {
  id: string;
  label: string;
}
/**
 * TrackedItem is one row in the Tag workflow's item picker — mirrors
 * internal/api's libraryTrackedItem, served from GET /api/modes/{mode}/tracked
 * for EVERY mode (items for Movies, series for Series, scenes for Adult). ID is
 * the library row id (a library_scenes.id for Adult, which is exactly the
 * {sceneId} the scene-tag routes take). Tags is the item's current tag labels
 * (a local tag has no numeric id — it's the label string itself, matching
 * TagEntry.ID).
 * TmdbId/Year are additive, present only for Movies/Series (both carry a TMDB
 * identity in the library); they are absent for Adult scenes, which are keyed
 * on (box, sceneId) with no TMDB id. Discover's existing-library row uses
 * TmdbId to lazily fetch each card's poster + availability and to drive
 * auto-grab; Year is display-only. The Tag picker (this type's original
 * caller) ignores both.
 */
export interface TrackedItem {
  id: number /* int64 */;
  title: string;
  tags: string[];
  tmdbId?: number /* int */;
  year?: number /* int */;
}
/**
 * ConnectionTestRequest is POST /api/connections/test's body — enough to
 * construct a client and make one real, read-only call (Settings' "Test"
 * button). Nothing is persisted, so APIKey here is a PLAIN string (not the
 * three-state *string of ConnectionUpsertRequest): a test always sends exactly
 * what's currently typed. Mirrors internal/api.ConnectionTestRequest.
 */
export interface ConnectionTestRequest {
  service: string;
  url: string;
  username?: string;
  apiKey?: string;
}
/**
 * ConnectionTestResult is POST /api/connections/test's response. A false OK
 * with a populated Error is the normal "wrong URL / wrong key" shape, not a
 * server-side failure. Mirrors internal/api.ConnectionTestResult.
 */
export interface ConnectionTestResult {
  ok: boolean;
  error?: string;
}
/**
 * AIProviderResponse / AIProviderRequest back GET/PUT /api/settings/ai-provider
 * — which AI backend every AI-assisted feature uses. Provider is one of
 * "ollama", "openai", "gemini", "anthropic".
 */
export interface AIProviderResponse {
  provider: string;
}
export interface AIProviderRequest {
  provider: string;
}
/**
 * AIModelResponse / AIModelRequest back GET/PUT /api/settings/ai-model — the
 * model name the configured provider should use (empty string = unset).
 */
export interface AIModelResponse {
  model: string;
}
export interface AIModelRequest {
  model: string;
}
/**
 * QualityPrefsResponse / QualityPrefsRequest back
 * GET/PUT /api/modes/{mode}/quality-prefs — Movies, Series, and Adult (the
 * Discover detail popup's availability grid applies to all three, so all
 * three get a configurable default; this used to say "Movies/Series only,
 * Adult has no Search workflow," which stopped being true once Adult grew
 * its own availability-popup search path). Tier is one of "low", "medium",
 * "high", "lossless"; MaxResolution is one of 480/720/1080/2160, or 0 for
 * "no cap" (a SOFT cap — see internal/quality's own package doc: it never
 * excludes a result outside the cap, only prefers at-or-below-cap when
 * choosing). Protocol is "usenet", "torrent", or "" for no preference.
 */
export interface QualityPrefsResponse {
  tier: string;
  maxResolution: number /* int */;
  protocol: string;
}
export interface QualityPrefsRequest {
  tier: string;
  maxResolution: number /* int */;
  protocol: string;
}
/**
 * NamingPresetResponse / NamingPresetRequest back
 * GET/PUT /api/modes/{mode}/naming-preset (Movies/Series only). Preset is one
 * of "jellyfin" (default) or "legacy".
 */
export interface NamingPresetResponse {
  preset: string;
}
export interface NamingPresetRequest {
  preset: string;
}
/**
 * LibraryRootFolderResponse / LibraryRootFolderRequest back
 * GET/PUT /api/modes/{mode}/library/root-folder — the free-typed root folder
 * SAK scans/imports into for a mode. The Settings UI exposes this for
 * Movies/Series only (matching the old renderLibrarySettings), even though the
 * backend key now exists for Adult too.
 */
export interface LibraryRootFolderResponse {
  path: string;
}
export interface LibraryRootFolderRequest {
  path: string;
}
/**
 * KidsRootPathResponse / KidsRootPathRequest back
 * GET/PUT /api/modes/{mode}/rename/kids-root-path (Movies/Series only — the
 * endpoint 400s for other modes). Empty Path turns Kids classification off.
 */
export interface KidsRootPathResponse {
  path: string;
}
export interface KidsRootPathRequest {
  path: string;
}
/**
 * PHashThresholdResponse / PHashThresholdRequest back
 * GET/PUT /api/modes/{mode}/phash-threshold — the Dedup perceptual-hash
 * similarity cut (per-frame average Hamming bits). Valid range 0–64; the
 * frontend mirrors that bound before submitting (backend re-validates).
 */
export interface PHashThresholdResponse {
  threshold: number /* int */;
}
export interface PHashThresholdRequest {
  threshold: number /* int */;
}
/**
 * ConfidenceThresholdResponse / ConfidenceThresholdRequest back
 * GET/PUT /api/modes/{mode}/match-confidence-threshold — the Rename
 * match-confidence cut (a 0–100 percentage). The frontend mirrors that bound
 * before submitting (backend re-validates).
 */
export interface ConfidenceThresholdResponse {
  threshold: number /* int */;
}
export interface ConfidenceThresholdRequest {
  threshold: number /* int */;
}
/**
 * IdentifyEnabledResponse / IdentifyEnabledRequest back
 * GET/PUT /api/modes/{mode}/identify-enabled — Adult's phash-first
 * identification toggle (default true). ADULT-ONLY: the endpoint 400s for any
 * other mode, so the Settings UI only renders this control in the Adult
 * context.
 */
export interface IdentifyEnabledResponse {
  enabled: boolean;
}
export interface IdentifyEnabledRequest {
  enabled: boolean;
}
/**
 * RecheckIntervalResponse / RecheckIntervalRequest back
 * GET/PUT /api/settings/recheck-interval — the background recheck cadence in
 * whole seconds. GLOBAL (not per-mode). 0 = off (the opt-in default); a
 * negative value is rejected, so the frontend mirrors that >= 0 bound.
 */
export interface RecheckIntervalResponse {
  intervalSeconds: number /* int */;
}
export interface RecheckIntervalRequest {
  intervalSeconds: number /* int */;
}
/**
 * NetscanFinding is one entry from the LAN-discovery probe endpoints
 * (GET /api/netscan/known, POST /api/netscan/host) — an unauthenticated,
 * spoofable HINT to verify, never a confirmed fact. Mirrors
 * internal/netscan.Finding. Service is one of "prowlarr" | "qbittorrent" |
 * "nzbget" | "jellyfin".
 */
export interface NetscanFinding {
  service: string;
  url: string;
  label: string;
}
/**
 * NetscanHostRequest is POST /api/netscan/host's body — probe one
 * operator-supplied host/LAN IP across the known services' default ports (the
 * server refuses any non-private host).
 */
export interface NetscanHostRequest {
  host: string;
}
/**
 * NetscanProwlarrKeyRequest / NetscanProwlarrKeyResponse back
 * POST /api/netscan/prowlarr-key — the one explicit action that reads a
 * Prowlarr instance's live API key from its unauthenticated /initialize.json.
 * A fetched key must be treated as touched by the connection form (see
 * src/api/settings.ts), or the three-state upsert would drop it as "untouched".
 */
export interface NetscanProwlarrKeyRequest {
  url: string;
}
export interface NetscanProwlarrKeyResponse {
  apiKey: string;
}
/**
 * Genre is one TMDB genre — mirrors tmdb.Genre's wire shape. Backs GET
 * /api/modes/{mode}/discover/genres (a movie or TV genre list depending on
 * {mode}'s media type) and is the reference list a "genre" slider's
 * FilterValue picks from.
 */
export interface Genre {
  id: number /* int */;
  name: string;
}
/**
 * Studio is a well-known movie production company — mirrors tmdb.Studio.
 * Backs GET /api/discover/studios, the fixed seed-list reference a "browse
 * by studio" row / "studio" slider's FilterValue picks from. Movies-only —
 * TMDB companies are a movie-catalog concept with no TV equivalent (see
 * Network below for TV's parallel concept).
 */
export interface Studio {
  id: number /* int */;
  name: string;
}
/**
 * Network is a well-known TV network/streaming service — mirrors
 * tmdb.Network. Backs GET /api/discover/networks, Studio's direct sibling
 * for the TV catalog (TV-only, symmetric restriction to Studio's
 * movies-only one).
 */
export interface Network {
  id: number /* int */;
  name: string;
}
/**
 * Keyword is one TMDB keyword search result — mirrors tmdb.Keyword. Backs
 * GET /api/discover/keywords?q=, the free-text lookup an admin slider editor
 * uses to resolve typed text (e.g. "heist") into the numeric TMDB keyword id
 * a "keyword" filter_type slider actually stores as FilterValue — unlike
 * Genre/Studio/Network, TMDB has no fixed enumerable keyword list to serve
 * as a seed list.
 */
export interface Keyword {
  id: number /* int */;
  name: string;
}
/**
 * Slider is one admin-defined custom Discover row — mirrors
 * discoversliders.Slider's wire shape. FilterType is one of "genre" |
 * "keyword" | "studio" | "network" | "upcoming" | "trending" | "popular";
 * Target restricts results to "movie" | "tv" | "mixed". FilterValue is a
 * stringified TMDB id (genre/studio/network/keyword) and is empty for the
 * three fixed feeds (upcoming/trending/popular) — see
 * discoversliders.Store's validate for the enforced pairing rule.
 */
export interface Slider {
  id: number /* int */;
  title: string;
  filterType: string;
  filterValue?: string;
  target: string;
  sortOrder: number /* int */;
  enabled: boolean;
  createdAt: string;
  updatedAt: string;
}
/**
 * SliderUpsertRequest is the body of POST /api/discover/sliders (create) and
 * PUT /api/discover/sliders/{id} (update) — every editable field, mirroring
 * discoversliders.Store.Create/Update's parameters exactly. Nothing in a
 * slider is a secret, so unlike ConnectionUpsertRequest.APIKey every field
 * here is a plain (non-pointer) required value — there is no "preserve
 * unchanged" partial-update mode; a save always sends the full slider.
 */
export interface SliderUpsertRequest {
  title: string;
  filterType: string;
  filterValue?: string;
  target: string;
  enabled: boolean;
}
/**
 * SliderReorderRequest is POST /api/discover/sliders/reorder's body — ids in
 * display order, covering every existing slider exactly once. One explicit
 * "here is the full new order" action, not a per-item bulk mutation (see
 * discoversliders.Store.Reorder's doc comment for why).
 */
export interface SliderReorderRequest {
  ids: number /* int */[];
}
/**
 * --- Adult Discover "newest" rows (internal/adultnewest) — Prowlarr-backed,
 * not TMDB-backed like Slider above. RowType is "movie" | "scene" |
 * "performer" | "studio"; GenreFilter is always optional (every row type can
 * be freely narrowed by genre or left unfiltered — unlike Slider's
 * FilterValue there is no required/forbidden pairing rule). See
 * adultnewest.Row and internal/api/adult_newest_rows.go.
 */
export interface AdultNewestRow {
  id: number /* int */;
  title: string;
  rowType: string;
  genreFilter?: string;
  sortOrder: number /* int */;
  enabled: boolean;
  createdAt: string;
  updatedAt: string;
}
/**
 * AdultNewestRowUpsertRequest is the body of POST /api/modes/adult/newest-rows
 * (create) and PUT /api/modes/adult/newest-rows/{id} (update) — mirrors
 * SliderUpsertRequest's convention: every editable field, no secrets, no
 * partial-update mode.
 */
export interface AdultNewestRowUpsertRequest {
  title: string;
  rowType: string;
  genreFilter?: string;
  enabled: boolean;
}
/**
 * AdultNewestRowReorderRequest is POST /api/modes/adult/newest-rows/reorder's
 * body — mirrors SliderReorderRequest exactly.
 */
export interface AdultNewestRowReorderRequest {
  ids: number /* int */[];
}
/**
 * AdultNewestReleaseItem is one entry in a resolved adult newest row — the
 * enriched result of matching a Prowlarr release to a TPDB/StashDB/FansDB
 * entity (internal/adultnewest's background scan job). Deliberately the same
 * shape as AdultDiscoverItem's display-relevant fields (Title/Studio/Date/
 * Image/Source) so AdultCard/EntityCard/DetailPopup need no changes to
 * render it — see this feature's plan, Stage 3.
 */
export interface AdultNewestReleaseItem {
  id: string;
  title: string;
  studio: string;
  date: string;
  image: string;
  source: string;
  rowType: string;
  /**
   * DurationSeconds is the matched entity's runtime, 0 if unknown — see
   * adultnewest.MatchedRelease.EntityDurationSeconds's doc comment. Added
   * specifically so the frontend can build a real grab request instead of
   * hardcoding 0 (a live bug: Adult's auto-grab scorer never re-fetches a
   * real runtime, so a 0 here silently fails to auto-qualify anything).
   */
  durationSeconds: number /* int */;
  /**
   * ReleaseTitle is the raw Prowlarr release title that first matched this
   * entity — see adultnewest.MatchedRelease.FirstSeenReleaseTitle's doc
   * comment. Used as the Grab-time Prowlarr search query in place of
   * reconstructing one from Title/Studio, which included tokens (e.g.
   * TPDB's "S6:E10" episode notation) real indexer filenames never
   * contain. "" for Studio/Performer rows and for entities matched before
   * this field existed.
   */
  releaseTitle?: string;
  genres?: string[];
  performers?: string[];
}
/**
 * TraktStatusResponse is GET /api/trakt/status's response — the general
 * "is Trakt usable right now" summary, consumed by both Settings (to render
 * configured/linked state and pre-fill the client_id field via ClientID)
 * and the Discover watchlist row. An unconfigured connection returns the
 * zero value (Configured: false), not an error. ClientID is not secret
 * (Trakt sends it as a plain header on every request, same as
 * ConnectionSummary.URL's pre-fill convention) — never the client_secret or
 * tokens themselves.
 */
export interface TraktStatusResponse {
  configured: boolean;
  linked: boolean;
  clientId?: string;
  tokenExpiresAt?: string;
}
/**
 * TraktCredentialsRequest is PUT /api/trakt/credentials's body — the
 * operator-entered Trakt application. ClientSecret follows the same
 * three-state rule as ConnectionUpsertRequest.APIKey (nil = preserve
 * stored secret, "" = clear, non-empty = set) — see that field's doc
 * comment for the full rule; a naive `clientSecret?: string` would
 * silently wipe the stored secret on an untouched save here too.
 */
export interface TraktCredentialsRequest {
  clientId: string;
  clientSecret?: string;
}
/**
 * TraktDeviceStartResponse is POST /api/trakt/device/start's response —
 * everything the frontend needs to show the operator (a code to enter and
 * a URL to visit) and to know how often to call POST /api/trakt/device/poll.
 * The device_code itself (the secret the server polls with) is deliberately
 * not included; polling is server-side.
 */
export interface TraktDeviceStartResponse {
  userCode: string;
  verificationUrl: string;
  expiresIn: number /* int */;
  interval: number /* int */;
}
/**
 * TraktDevicePollResponse is POST /api/trakt/device/poll's response — one
 * non-blocking poll attempt against the in-progress device authorization
 * started by TraktDeviceStartResponse. Deliberately a separate endpoint
 * from TraktStatusResponse above: this one drives the Connect-flow UI's
 * polling loop, the other answers "is Trakt usable right now" everywhere
 * else. Linked true means tokens were saved and the flow is done; Pending
 * true means keep polling; both false (a denied or expired device code)
 * means the flow is over without success — the frontend's own
 * client-side deadline (from TraktDeviceStartResponse.ExpiresIn) and the
 * 409 a subsequent poll gets (the server clears the flow on any terminal
 * outcome) are what surface that to the operator, since there's no
 * separate "denied"/"expired" field on the wire.
 */
export interface TraktDevicePollResponse {
  linked: boolean;
  pending: boolean;
}
/**
 * TraktWatchlistItem is one entry of GET /api/trakt/watchlist's response —
 * a near-direct mirror of internal/trakt.WatchlistItem's fields. Note this
 * is deliberately NOT DiscoverItem's shape: Trakt's watchlist API provides
 * no poster/overview/rating at all, so there is nothing to mirror there;
 * any TMDB enrichment by TmdbId is the frontend's job, not done server-side
 * (an N-item watchlist would otherwise mean N extra TMDB calls per page
 * load).
 */
export interface TraktWatchlistItem {
  type: string;
  title: string;
  year?: number /* int */;
  tmdbId: number /* int */;
}
/**
 * BrowseEntry is one directory GET /api/browse's response lists — a
 * subdirectory of the requested path, never a file (the endpoint's root-
 * folder picker use case has no reason to surface files).
 */
export interface BrowseEntry {
  name: string;
  path: string;
}
/**
 * BrowseResponse is GET /api/browse's response — Path echoes back the
 * resolved, cleaned directory that was listed (empty when no path was
 * requested, in which case Entries is the fixed set of browsable roots
 * themselves). See internal/api/browse.go for the allowlist and validation
 * this endpoint enforces.
 */
export interface BrowseResponse {
  path: string;
  entries: BrowseEntry[];
}
