// Code generated by tygo. DO NOT EDIT.

//////////
// source: dto.go
/*
Package apidto is sakms's curated, exported request/response DTO
boundary for the future frontend's generated TypeScript API client (see
.omc/plans/frontend-redesign-seerr.md, Stage 0 / Guardrail #4).

Why this package exists: today's handlers decode/encode JSON using
unexported request structs (e.g. internal/api's upsertConnectionRequest)
and raw internal/domain structs (e.g. tmdb.Item, connections.Summary)
encoded directly. A source-parsing codegen tool CAN see unexported types
if pointed at internal/api directly, but that would emit a TypeScript
type for every internal handler struct across the whole package — far
more than a frontend client should ever import, and it would silently
change shape every time an unrelated handler's internal request struct
changed. This package is the deliberate alternative: a small, hand-picked,
EXPORTED set of types that mirror only what a frontend actually needs to
send/receive, kept in one place a codegen tool can be pointed at in
isolation (see internal/apidto/gen).

Scope (Stage 0 / Stage 1 only — see README.md "Scope grows per stage"):
auth boot (setup/login/status/mode/OIDC config/API key management) and
Discover's read-only surface (poster items + availability badges), the
exact set Stage 1's toolchain slice consumes. Stages 2-4 add their own
DTOs here as their frontend work lands — this file is a starting point,
not a final inventory, per Guardrail #4.

These types are currently PARALLEL COPIES of the shapes already produced
by internal/api's handlers (authStatusResponse, oidcStatusResponse,
tmdb.Item, etc.) and internal/auth's APIKeyStatus. Stage 0 defines them
but does not wire any handler to use them — no frontend exists yet to
prove a wiring change against, and touching the auth handlers here would
add lockout risk for zero benefit (see README.md). Stage 1 is expected to
converge the real handlers onto these exact types, at which point the
parallel definitions in internal/api collapse into a single source of
truth here.

Field names, JSON tags, and types below match the current wire format
exactly (same lowerCamelCase JSON keys the existing handlers already
emit) so that a future Stage-1 handler swap is a type substitution, not a
wire-format change.

IMPORTANT — three-state optional-secret fields (Guardrail #5): see
ConnectionUpsertRequest.APIKey's doc comment and README.md's "Three-state
secret mapping rule" section before generating or consuming a TypeScript
client for any *string field in this package.
*/

/**
 * SetupRequest is the body of POST /api/auth/setup — SAK's one-time,
 * first-run login bootstrap. Mode selects the auth strategy ("password" is
 * the default when Mode is omitted, "oidc", or "none").
 * AcknowledgeInsecure must be true to select Mode "none". The four
 * OIDC* fields are required together, and only meaningful, when
 * Mode == "oidc".
 */
export interface SetupRequest {
  username: string;
  password: string;
  mode: string;
  acknowledgeInsecure: boolean;
  oidcIssuerUrl?: string;
  oidcClientId?: string;
  oidcClientSecret?: string;
  oidcRedirectUrl?: string;
}
/**
 * SetupResponse is returned by POST /api/auth/setup only for "oidc"-mode
 * setup (empty body / 204 for "password"/"none"). Exactly one of APIKey or
 * APIKeyNote is populated: APIKey is a one-time break-glass credential
 * revealed ONCE, never retrievable again; APIKeyNote is present instead
 * when SAKMS_API_KEY is set via environment (no settings-managed key is
 * minted in that case — the env value IS the break-glass credential).
 */
export interface SetupResponse {
  apiKey?: string;
  apiKeyNote?: string;
}
/**
 * LoginRequest is the body of POST /api/auth/login — only meaningful when
 * the active auth mode is "password" (checked server-side; "oidc" logs in
 * via a full-page redirect to /api/auth/oidc/login instead, and "none" has
 * no login step).
 */
export interface LoginRequest {
  username: string;
  password: string;
}
/**
 * AuthStatusResponse is GET /api/auth/status's response — the one call the
 * frontend's boot sequence makes before it knows anything else about the
 * instance, deciding between the setup wizard, the login screen, and the
 * app (see Guardrail #2's 3-way boot branch). Mode is one of "password",
 * "oidc", or "none".
 */
export interface AuthStatusResponse {
  configured: boolean;
  authenticated: boolean;
  mode: string;
}
/**
 * AuthModeResponse is GET /api/auth/mode's response.
 */
export interface AuthModeResponse {
  mode: string;
}
/**
 * AuthModeRequest is PUT /api/auth/mode's body — switches the ALREADY
 * authenticated operator's active auth mode. AcknowledgeInsecure must be
 * true to switch into "none" (mirrors SetupRequest's same field for the
 * first-run case).
 */
export interface AuthModeRequest {
  mode: string;
  acknowledgeInsecure: boolean;
}
/**
 * OIDCStatusResponse is GET /api/auth/oidc's response. HasSecret reports
 * whether a client secret is currently stored; the secret itself is NEVER
 * returned (mirrors ConnectionSummary's HasAPIKey/KeySuffix pattern for the
 * same reason — see README.md).
 */
export interface OIDCStatusResponse {
  issuerUrl: string;
  clientId: string;
  redirectUrl: string;
  hasSecret: boolean;
}
/**
 * OIDCConfigRequest is PUT /api/auth/oidc's body — sets/replaces the
 * OIDC provider config for an already-configured instance. Unlike
 * ConnectionUpsertRequest.APIKey, ClientSecret here is a plain (non-pointer)
 * required field: every PUT to this endpoint must supply the full config,
 * there is no "leave secret unchanged" partial-update mode for OIDC config
 * today.
 */
export interface OIDCConfigRequest {
  issuerUrl: string;
  clientId: string;
  clientSecret: string;
  redirectUrl: string;
}
/**
 * APIKeyStatusResponse is GET /api/apikey's response. Source is one of
 * "env" (SAKMS_API_KEY active), "settings" (a regenerated key is stored),
 * or "none" (no key exists). The key itself is never returned here — only
 * KeySuffix, matching ConnectionSummary's masked-display convention.
 */
export interface APIKeyStatusResponse {
  hasKey: boolean;
  keySuffix?: string;
  source: string;
}
/**
 * APIKeyRegenerateResponse is POST /api/apikey/regenerate's response — the
 * one place the full API key crosses the API boundary. Shown once, never
 * retrievable again afterward (same one-shot-reveal contract as
 * SetupResponse.APIKey).
 */
export interface APIKeyRegenerateResponse {
  apiKey: string;
  keySuffix: string;
}
/**
 * ModeStatus reports what's configured for one mode (Mode is one of
 * "movies", "series", "adult") — enough for the setup wizard to know which
 * steps are already done and skip past them.
 */
export interface ModeStatus {
  mode: string;
  available: boolean;
  arrConfigured: boolean;
  allowlistCount: number /* int */;
}
/**
 * SetupStatusResponse is GET /api/setup/status's response — a pure read
 * model over what's already configured, driving whether the setup wizard
 * shows itself at all and which of its steps it can skip.
 */
export interface SetupStatusResponse {
  modes: ModeStatus[];
  jellyfinConfigured: boolean;
  ollamaConfigured: boolean;
  dismissed: boolean;
  anyConfigured: boolean;
}
/**
 * DismissSetupRequest is PUT /api/setup/dismissed's body.
 */
export interface DismissSetupRequest {
  dismissed: boolean;
}
/**
 * DiscoverItem is one TMDB trending/popular result for Movies/Series
 * Discover (GET /api/modes/{mode}/discover) — mirrors tmdb.Item's exact
 * wire shape. MediaType is "movie" or "tv".
 */
export interface DiscoverItem {
  id: number /* int */;
  title: string;
  posterPath: string;
  overview: string;
  releaseDate: string;
  voteAverage: number /* float64 */;
  mediaType: string;
}
/**
 * AdultDiscoverItem is one TPDB scene result for Adult Discover
 * (GET /api/modes/adult/discover) — scene-shaped, not title-shaped (Studio
 * substitutes for a studio/site name). Date is TPDB's release date string,
 * unparsed. Image is the scene thumbnail URL served from TPDB's own image CDN
 * (cdn.theporndb.net); it is frequently empty (many scenes have no art), so
 * the client must render a text-only card when blank and route non-empty
 * values through the image proxy (GET /api/images/proxy?url=), never
 * hot-linking TPDB directly (plan Decision #7). DurationSeconds is the
 * scene's pre-grab runtime in seconds (see internal/tpdbrest.Scene.Duration
 * for sourcing/confidence: documented-shape + corroborated by two
 * independent sources, not live-confirmed against a real TPDB instance); it
 * may be 0 (unknown), which the auto-grab bitrate scorer (Stage 2) must
 * treat as "skip the pre-grab bitrate check," never a real zero-length
 * runtime or a divide-by-zero input.
 */
export interface AdultDiscoverItem {
  id: string;
  title: string;
  studio: string;
  date: string;
  image: string;
  durationSeconds: number /* int */;
}
/**
 * AvailabilityResponse is GET /api/modes/{mode}/availability's response —
 * backs a Discover card's availability badge (Stage 1 scope: "poster cards
 * with availability badges" per the plan). CheckedAt is an RFC3339Nano
 * timestamp of when the probe ran.
 */
export interface AvailabilityResponse {
  available: boolean;
  releaseCount: number /* int */;
  checkedAt: string;
}
/**
 * ConnectionSummary is one entry of GET /api/connections's response — what's
 * safe to expose about a configured connection: never the secret itself,
 * only whether one is set and its last 4 characters (masked display).
 * Included here alongside ConnectionUpsertRequest even though the
 * Connections/Settings UI itself isn't built until Stage 4 — see
 * ConnectionUpsertRequest's doc comment for why.
 */
export interface ConnectionSummary {
  service: string;
  url: string;
  username?: string;
  hasApiKey: boolean;
  keySuffix?: string;
  updatedAt: string;
}
/**
 * ConnectionUpsertRequest is PUT /api/connections/{service}'s body —
 * included in Stage 0's curated set (ahead of Stage 4, when Settings'
 * actual frontend lands) specifically BECAUSE it carries the single most
 * safety-critical mapping rule in this whole DTO boundary (Guardrail #5)
 * and needed to be proven against the chosen codegen tool before that tool
 * choice was finalized, not discovered as a surprise in Stage 4.
 * APIKey is a pointer so the three states a client MUST be able to express
 * survive the JSON round-trip (json.Decode sets it accordingly; omitempty
 * only affects marshaling, never decoding):
 *   - field ABSENT from the request body entirely (nil)  → preserve the
 *     stored secret. The server never sends the real secret back to a
 *     client (see ConnectionSummary above — only HasAPIKey/KeySuffix are
 *     exposed), so an untouched, blank key input MUST be omitted from the
 *     JSON body, never sent as "".
 *   - field present as ""  (&"")                          → explicitly
 *     clear the stored secret (e.g. switching to a service that needs
 *     none, like Ollama).
 *   - field present, non-empty  (&"sk-...")                → set/replace
 *     the stored secret.
 * TypeScript CANNOT express this three-way distinction as a type — both
 * a field absent entirely and a field present with an empty-string value
 * collapse to the same `string | undefined` a source-parsing generator
 * emits for a Go *string.
 * See README.md's "Three-state secret mapping rule" section for the
 * generated TypeScript shape and the load-bearing prose rule a frontend
 * MUST follow by convention (not by the type system) when building this
 * request body.
 */
export interface ConnectionUpsertRequest {
  url: string;
  username?: string;
  apiKey?: string;
}
/**
 * Grab mirrors internal/grabs.Grab's exact wire shape — the record SAK keeps
 * for one release it has sent to a download client. Exposed here so the
 * frontend's Grabs view and the auto-grab response share one generated
 * TypeScript type instead of hand-duplicating the shape.
 * FlaggedForReview / FlagReason are the ADVISORY post-grab mislabel signal
 * (set by checkImportHandler via internal/autograb.RuntimeMismatch, Movies
 * only for now): they do NOT mean the import failed — the import already
 * succeeded — only that the imported file's runtime looked inconsistent with
 * its metadata and a human might want to eyeball it. The Grabs view must say
 * so in its copy, never present the flag as an error.
 */
export interface Grab {
  id: number /* int64 */;
  mode: string;
  title: string;
  tmdbId?: number /* int */;
  tvdbId?: number /* int */;
  seasonNumber?: number /* int */;
  episodeNumber?: number /* int */;
  seasonSpecified?: boolean;
  qualityProfileId?: number /* int */;
  indexer: string;
  protocol: string;
  downloadClient: string;
  clientRef?: string;
  status: string;
  rootFolderPath: string;
  flaggedForReview?: boolean;
  flagReason?: string;
  createdAt: string;
  updatedAt: string;
}
/**
 * AutoGrabRequest is POST /api/modes/{mode}/autograb's body — Discover's
 * one-click unattended grab trigger for exactly one title/scene. Which fields
 * matter is mode-specific:
 *   - Movies:  TMDBID (drives the id-scoped Prowlarr search AND the TMDB
 *     runtime lookup the bitrate scorer needs) + Title.
 *   - Series:  TMDBID + Title + SeasonNumber/EpisodeNumber/SeasonSpecified —
 *     the picker's selection ("one click PER season/episode selection", per
 *     the plan's per-mode nuance). No per-episode runtime exists pre-grab
 *     today, so Series candidates all grade as unknown-bitrate and the call
 *     returns the manual fallback list rather than auto-grabbing (documented
 *     behavior, not a bug). SeasonSpecified must be threaded through so a
 *     deliberate Season-0/Specials grab isn't misread as "no season picked"
 *     (see grabs.Grab.SeasonSpecified / checkImportHandler).
 *   - Adult:   Title + Studio (the free-text Prowlarr query, mirroring
 *     availability.CheckAdultScene) + DurationSeconds (TPDB's pre-grab
 *     runtime → the scorer's RuntimeSeconds; 0 = unknown, handled neutrally).
 */
export interface AutoGrabRequest {
  title: string;
  tmdbId?: number /* int */;
  studio?: string;
  seasonNumber?: number /* int */;
  episodeNumber?: number /* int */;
  seasonSpecified?: boolean;
  durationSeconds?: number /* int */;
}
/**
 * AutoGrabCandidate is one graded release in an auto-grab manual-fallback list
 * (AutoGrabResponse.Candidates). It pairs the grade (Status = why it did/didn't
 * auto-qualify, Score = the bitrate ranking key) with the exact release
 * identity the frontend needs to grab it manually via
 * POST /api/modes/{mode}/search/grab — one release per click, never a batch.
 * Status is one of internal/autograb.Status's values ("qualified",
 * "below-floor", "mislabeled", "low-seeders", "unknown-bitrate",
 * "unknown-resolution").
 */
export interface AutoGrabCandidate {
  title: string;
  indexer: string;
  protocol: string;
  downloadUrl: string;
  size: number /* int64 */;
  seeders: number /* int */;
  status: string;
  score: number /* float64 */;
  impliedMbps: number /* float64 */;
  floorMbps: number /* float64 */;
  qualified: boolean;
}
/**
 * AutoGrabResponse is POST /api/modes/{mode}/autograb's result — exactly one
 * of two outcomes:
 *   - Grabbed == true:  a release cleared every gate and was sent to the
 *     download client. Grab is the recorded grab (also visible in the Grabs
 *     view); Candidates is empty.
 *   - Grabbed == false (Fallback == true): nothing auto-qualified —
 *     Candidates is the ranked manual pick list (best bitrate score first,
 *     the SAME score that gated auto-grab), each row labeled with why it
 *     didn't qualify. The operator picks exactly one to grab; Grab is nil.
 * Message is a short human summary for the UI.
 */
export interface AutoGrabResponse {
  grabbed: boolean;
  fallback: boolean;
  message: string;
  grab?: Grab;
  candidates?: AutoGrabCandidate[];
}
/**
 * Candidate is one file in a Dedup proposal's duplicate group — the shape the
 * Dedup view (frontend/src/screens/Dedup.tsx) renders one table row from. A
 * CURATED subset of internal/proposals.Candidate: only the fields the view
 * actually displays (Label/Path/Resolution/Codec/BitRate) plus Winner, the
 * keeper-vs-duplicate flag. Winner==true is the "tracked copy" the group keeps;
 * every other candidate is a duplicate the Apply removes (see
 * internal/dedup.ApplyLibrary*). Wire order is load-bearing: DedupApplyRequest's
 * KeepIndex is an ARRAY INDEX into this exact slice (proposals.Proposal.Candidates
 * order), so the client MUST render candidates in received order and never sort
 * them, or the index it sends resolves to the wrong file. proposals.Candidate's
 * TrackedID/PHash are intentionally omitted — the view reads neither, and this
 * package curates to what the frontend consumes (see the Proposal doc / package doc).
 */
export interface Candidate {
  label: string;
  path: string;
  resolution: number /* int */;
  codec: string;
  bitRate: number /* int64 */;
  winner: boolean;
}
/**
 * Proposal is one staged review-queue row as the Rename/Purge/Dedup views consume
 * it. SourceName/RootFolderPath/Reason are always present; Title/Year are only
 * meaningful once Status is pending/applied; Reason explains an unmatched row;
 * DraftID is set once a successful submit-draft ("give back") has run, so the
 * button renders as already-done and can't re-submit. Studio/Date/PHash are
 * Adult-only (captured from Adult identification); SeasonNumber/EpisodeNumber
 * are Series-only (a season-pack orphan produces one proposal per episode).
 * Candidates is Dedup-only: the duplicate group's files, exactly one flagged
 * Winner (the keeper); Rename/Purge never populate it (it's absent from their
 * wire rows, so the shared TS type carries it as optional).
 */
export interface Proposal {
  id: number /* int64 */;
  status: string;
  sourceName: string;
  rootFolderPath: string;
  title?: string;
  year?: number /* int */;
  seasonNumber?: number /* int */;
  episodeNumber?: number /* int */;
  studio?: string;
  date?: string;
  phash?: string;
  reason?: string;
  draftId?: string;
  candidates?: Candidate[];
}
/**
 * AllowlistAddRequest is the body of POST /api/modes/{mode}/purge/allowlist —
 * adds one tag rule to a mode's Purge allowlist. Mirrors internal/api's
 * unexported addAllowlistTagRequest exactly. Adding a tag already present is
 * not an error (see allowlist.Store.Add).
 */
export interface AllowlistAddRequest {
  tag: string;
}
/**
 * RepickRequest is the body of POST /api/proposals/{id}/repick — Rename's
 * manual-override path when Scan's automatic TMDB match was wrong or scored too
 * low to auto-accept (Movies/Series only; Adult identifies via a different id
 * space with its own give-back correction). TMDBID and Title are both required
 * and carry the NEWLY chosen match from the tmdb-search result, never the
 * proposal's current tmdbId; Year is optional (parsed from the result's
 * release date when present). Mirrors internal/api's repickProposalRequest.
 */
export interface RepickRequest {
  tmdbId: number /* int */;
  title: string;
  year?: number /* int */;
}
/**
 * DedupApplyRequest is the OPTIONAL body of POST /api/proposals/{id}/apply when
 * the proposal is a Dedup group (Rename/Purge send an empty body and ignore
 * these fields — see internal/api's applyProposalRequest, which this mirrors).
 * Exactly one of two shapes is sent per Apply:
 *   - {keepIndex: N} — keep candidate N, delete every other candidate in the
 *     group. N is an ARRAY INDEX into Proposal.Candidates in received order
 *     (the radio the operator selected; the group's Winner is pre-selected).
 *     KeepIndex MUST be sent even when it is 0 — a falsy-guard that drops a
 *     literal 0 makes the backend fall back to its own auto-winner and can
 *     delete the file the operator actually chose to keep (dedup.ApplyLibrary
 *     indexes p.Candidates[keepIndex] directly).
 *   - {keepAll: true} — keep every candidate, delete nothing ("Keep All"). The
 *     conservative escape hatch when the group isn't really a duplicate.
 * KeepIndex is a pointer/omitempty so "keep all" omits it entirely rather than
 * sending 0 (which would mean "keep candidate 0").
 */
export interface DedupApplyRequest {
  keepIndex?: number /* int */;
  keepAll?: boolean;
}
/**
 * TagEntry is one entry in a mode's tag vocabulary — mirrors internal/api's
 * libraryTagEntry. A local tag has no numeric id, so ID and Label are the same
 * string value; ID exists only to keep the {id, label} shape the frontend's
 * datalist/lookup logic expects. Returned by both the Movies/Series generic
 * vocab route and Adult's dedicated scene-tag vocab route.
 */
export interface TagEntry {
  id: string;
  label: string;
}
/**
 * TrackedItem is one row in the Tag workflow's item picker — mirrors
 * internal/api's libraryTrackedItem, served from GET /api/modes/{mode}/tracked
 * for EVERY mode (items for Movies, series for Series, scenes for Adult). ID is
 * the library row id (a library_scenes.id for Adult, which is exactly the
 * {sceneId} the scene-tag routes take). Tags is the item's current tag labels
 * (a local tag has no numeric id — it's the label string itself, matching
 * TagEntry.ID).
 */
export interface TrackedItem {
  id: number /* int64 */;
  title: string;
  tags: string[];
}
