-- +goose Up
-- Claude 2026-08-04: fresh Postgres baseline (SQLite chain archived).
-- Reason: Postgres-only migration; deep-interview-sakms-postgres-migration.
-- Troubleshooting: ETL needs GENERATED BY DEFAULT AS IDENTITY for explicit ids.
-- Review if: live schema drifts; regenerate from sakms.db and re-diff.

-- +goose StatementBegin
CREATE OR REPLACE FUNCTION sakms_now() RETURNS text LANGUAGE sql VOLATILE AS $$
  SELECT to_char(clock_timestamp() AT TIME ZONE 'utc', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')
$$;
CREATE OR REPLACE FUNCTION sakms_now_sec() RETURNS text LANGUAGE sql VOLATILE AS $$
  SELECT to_char(clock_timestamp() AT TIME ZONE 'utc', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')
$$;
-- +goose StatementEnd

CREATE TABLE adult_newest_releases (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    row_type text NOT NULL,
    entity_id text NOT NULL,
    entity_source text NOT NULL,
    entity_title text NOT NULL,
    entity_studio text NOT NULL DEFAULT '',
    entity_image text NOT NULL DEFAULT '',
    entity_date text NOT NULL DEFAULT '',
    genres text NOT NULL DEFAULT '[]',
    first_seen_at text NOT NULL DEFAULT sakms_now(),
    entity_duration_seconds bigint NOT NULL DEFAULT 0,
    first_seen_release_title text NOT NULL DEFAULT '',
    performers text NOT NULL DEFAULT '[]',
    download_url text NOT NULL DEFAULT '',
    download_protocol text NOT NULL DEFAULT '',
    size_bytes bigint NOT NULL DEFAULT 0,
    browse_confirmed boolean NOT NULL DEFAULT false,
    feed_id bigint NOT NULL DEFAULT 0,
    feed_item_key text NOT NULL DEFAULT '',
    last_confirmed_seen bigint NOT NULL DEFAULT 0,
    gender text,
    UNIQUE (row_type, entity_source, entity_id)
);

CREATE TABLE adult_newest_rows (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title text NOT NULL,
    row_type text NOT NULL,
    genre_filter text NOT NULL DEFAULT '',
    sort_order bigint NOT NULL DEFAULT 0,
    enabled boolean NOT NULL DEFAULT true,
    created_at text NOT NULL DEFAULT sakms_now(),
    updated_at text NOT NULL DEFAULT sakms_now()
);

CREATE TABLE adult_newest_scene_matches (
    download_url text PRIMARY KEY,
    title text NOT NULL DEFAULT '',
    studio text NOT NULL DEFAULT '',
    image text NOT NULL DEFAULT '',
    date text NOT NULL DEFAULT '',
    genres text NOT NULL DEFAULT '[]',
    performers text NOT NULL DEFAULT '[]',
    duration_seconds bigint NOT NULL DEFAULT 0,
    box text NOT NULL DEFAULT '',
    matched_at text NOT NULL DEFAULT sakms_now()
);

CREATE TABLE adult_newest_seen (
    release_guid text PRIMARY KEY,
    seen_at text NOT NULL DEFAULT sakms_now()
);

CREATE TABLE availability_watch (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mode text NOT NULL,
    tmdb_id bigint NOT NULL DEFAULT 0,
    season bigint NOT NULL DEFAULT 0,
    episode bigint NOT NULL DEFAULT 0,
    studio text NOT NULL DEFAULT '',
    title text NOT NULL DEFAULT '',
    added_at text NOT NULL DEFAULT sakms_now(),
    last_checked_at text NOT NULL DEFAULT '',
    last_available bigint NOT NULL DEFAULT 0,
    UNIQUE (mode, tmdb_id, season, episode, studio, title)
);

CREATE TABLE connections (
    service text PRIMARY KEY,
    url text NOT NULL,
    api_key_encrypted text NOT NULL DEFAULT '',
    created_at text NOT NULL DEFAULT sakms_now(),
    updated_at text NOT NULL DEFAULT sakms_now(),
    username text NOT NULL DEFAULT ''
);

CREATE TABLE discover_row_cache (
    source text,
    cache_key text,
    payload text NOT NULL DEFAULT '[]',
    item_count bigint NOT NULL DEFAULT 0,
    page_size bigint NOT NULL DEFAULT 20,
    raw_pages bigint NOT NULL DEFAULT 0,
    exhausted bigint NOT NULL DEFAULT 0,
    refreshed_at text NOT NULL DEFAULT '',
    attempted_at text NOT NULL DEFAULT '',
    last_error text NOT NULL DEFAULT '',
    PRIMARY KEY (source, cache_key)
);

CREATE TABLE discover_sliders (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title text NOT NULL,
    filter_type text NOT NULL,
    filter_value text NOT NULL DEFAULT '',
    target text NOT NULL,
    sort_order bigint NOT NULL DEFAULT 0,
    enabled boolean NOT NULL DEFAULT true,
    created_at text NOT NULL DEFAULT sakms_now(),
    updated_at text NOT NULL DEFAULT sakms_now()
);

CREATE TABLE excluded_titles (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exclude_key text NOT NULL UNIQUE,
    mode text NOT NULL,
    tmdb_id bigint NOT NULL DEFAULT 0,
    title text NOT NULL DEFAULT '',
    excluded_at text NOT NULL DEFAULT sakms_now()
);

CREATE TABLE grabs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mode text NOT NULL,
    title text NOT NULL,
    tmdb_id bigint NOT NULL DEFAULT 0,
    tvdb_id bigint NOT NULL DEFAULT 0,
    quality_profile_id bigint NOT NULL DEFAULT 0,
    indexer text NOT NULL,
    protocol text NOT NULL,
    download_client text NOT NULL,
    client_ref text NOT NULL DEFAULT '',
    status text NOT NULL DEFAULT 'queued',
    root_folder_path text NOT NULL,
    created_at text NOT NULL DEFAULT sakms_now(),
    updated_at text NOT NULL DEFAULT sakms_now(),
    season_number bigint NOT NULL DEFAULT 0,
    episode_number bigint NOT NULL DEFAULT 0,
    season_specified boolean NOT NULL DEFAULT false,
    flagged_for_review boolean NOT NULL DEFAULT false,
    flag_reason text NOT NULL DEFAULT '',
    download_gid text NOT NULL DEFAULT '',
    download_status text NOT NULL DEFAULT '',
    download_staging_path text NOT NULL DEFAULT '',
    download_url_encrypted text NOT NULL DEFAULT '',
    retry_after text NOT NULL DEFAULT '',
    retry_count bigint NOT NULL DEFAULT 0,
    retry_reason text NOT NULL DEFAULT '',
    hold_until text NOT NULL DEFAULT ''
);

CREATE TABLE library_collections (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tmdb_collection_id bigint NOT NULL UNIQUE,
    name text NOT NULL
);

CREATE TABLE library_scenes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    box text NOT NULL,
    scene_id text NOT NULL,
    title text NOT NULL DEFAULT '',
    studio text NOT NULL DEFAULT '',
    date text NOT NULL DEFAULT '',
    file_path text NOT NULL DEFAULT '',
    root_folder_path text NOT NULL,
    phash text NOT NULL DEFAULT '',
    phash_file_size bigint NOT NULL DEFAULT 0,
    phash_file_mtime text NOT NULL DEFAULT '',
    created_at text NOT NULL DEFAULT sakms_now(),
    updated_at text NOT NULL DEFAULT sakms_now(),
    size bigint NOT NULL DEFAULT 0,
    quality_tier text NOT NULL DEFAULT '',
    UNIQUE (box, scene_id)
);

CREATE TABLE library_season_monitored (
    series_id bigint,
    season_number bigint,
    monitored boolean NOT NULL DEFAULT false,
    created_at text NOT NULL DEFAULT sakms_now(),
    updated_at text NOT NULL DEFAULT sakms_now(),
    PRIMARY KEY (series_id, season_number)
);

CREATE TABLE library_series (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tmdb_id bigint NOT NULL,
    tvdb_id bigint NOT NULL DEFAULT 0,
    title text NOT NULL,
    year bigint NOT NULL DEFAULT 0,
    root_folder_path text NOT NULL,
    created_at text NOT NULL DEFAULT sakms_now(),
    updated_at text NOT NULL DEFAULT sakms_now(),
    genres text NOT NULL DEFAULT '[]',
    "cast" text NOT NULL DEFAULT '[]',
    UNIQUE (tmdb_id)
);

CREATE TABLE node_keys (
    id text PRIMARY KEY,
    key_hash text NOT NULL,
    name text NOT NULL,
    approved_at text NOT NULL
);

CREATE TABLE node_max_jobs (
    node_id text PRIMARY KEY,
    max_jobs bigint NOT NULL,
    updated_at text NOT NULL,
    pause_dispatch boolean NOT NULL DEFAULT false,
    cpu_cap_percent bigint NOT NULL DEFAULT 0
);

CREATE TABLE node_path_mappings (
    node_id text,
    library_path_key text,
    node_path text NOT NULL,
    updated_at text NOT NULL,
    verification_status text NOT NULL DEFAULT 'unverified_bootstrap',
    verified_at text,
    PRIMARY KEY (node_id, library_path_key)
);

CREATE TABLE orphan_phashes (
    path text PRIMARY KEY,
    phash text NOT NULL DEFAULT '',
    phash_file_size bigint NOT NULL DEFAULT 0,
    phash_file_mtime text NOT NULL DEFAULT ''
);

CREATE TABLE parse_entity_sync (
    source text PRIMARY KEY,
    cursor text,
    synced_at text
);

CREATE TABLE parse_performers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    name_norm text NOT NULL,
    source text NOT NULL,
    ext_id text,
    updated_at text NOT NULL DEFAULT sakms_now()
);

CREATE TABLE parse_studios (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    name_norm text NOT NULL,
    source text NOT NULL,
    ext_id text,
    updated_at text NOT NULL DEFAULT sakms_now()
);

CREATE TABLE proposals (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mode text NOT NULL,
    workflow text NOT NULL,
    status text NOT NULL DEFAULT 'pending',
    source_name text NOT NULL,
    source_path text NOT NULL,
    root_folder_path text NOT NULL,
    title text NOT NULL DEFAULT '',
    tvdb_id bigint NOT NULL DEFAULT 0,
    tmdb_id bigint NOT NULL DEFAULT 0,
    quality_profile_id bigint NOT NULL DEFAULT 0,
    reason text NOT NULL DEFAULT '',
    tracked_id bigint NOT NULL DEFAULT 0,
    created_at text NOT NULL DEFAULT sakms_now(),
    applied_at text,
    candidates_json text NOT NULL DEFAULT '[]',
    foreign_id text NOT NULL DEFAULT '',
    item_type text NOT NULL DEFAULT '',
    studio text NOT NULL DEFAULT '',
    scene_date text NOT NULL DEFAULT '',
    draft_id text NOT NULL DEFAULT '',
    draft_submitted_at text,
    season_number bigint NOT NULL DEFAULT 0,
    episode_number bigint NOT NULL DEFAULT 0,
    year bigint NOT NULL DEFAULT 0,
    phash text NOT NULL DEFAULT '',
    duration_seconds bigint NOT NULL DEFAULT 0,
    give_back_box text NOT NULL DEFAULT '',
    give_back_scene_id text NOT NULL DEFAULT '',
    fingerprint_submitted_at text,
    extra_episode_numbers text NOT NULL DEFAULT '',
    genres text NOT NULL DEFAULT '[]',
    "cast" text NOT NULL DEFAULT '[]',
    phash_similarity double precision NOT NULL DEFAULT 0
);

CREATE TABLE pruning_rules (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    mode text NOT NULL,
    age_days bigint NOT NULL DEFAULT 0,
    size_bytes bigint NOT NULL DEFAULT 0,
    quality_tier_floor text NOT NULL DEFAULT '',
    enabled boolean NOT NULL DEFAULT true,
    created_at text NOT NULL DEFAULT sakms_now(),
    updated_at text NOT NULL DEFAULT sakms_now()
);

CREATE TABLE purge_allowlist (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mode text NOT NULL,
    tag text NOT NULL,
    created_at text NOT NULL DEFAULT sakms_now()
);

CREATE TABLE rss_feeds (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title text NOT NULL,
    feed_url text NOT NULL,
    target text NOT NULL,
    protocol text NOT NULL,
    sort_order bigint NOT NULL DEFAULT 0,
    enabled boolean NOT NULL DEFAULT true,
    created_at text NOT NULL DEFAULT sakms_now(),
    updated_at text NOT NULL DEFAULT sakms_now(),
    feed_url_encrypted text NOT NULL DEFAULT ''
);

CREATE TABLE service_connections (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind text NOT NULL,
    provider text NOT NULL,
    label text NOT NULL DEFAULT '',
    url text NOT NULL DEFAULT '',
    host text NOT NULL DEFAULT '',
    port bigint NOT NULL DEFAULT 0,
    tls boolean NOT NULL DEFAULT false,
    username text NOT NULL DEFAULT '',
    max_conns bigint NOT NULL DEFAULT 0,
    secret_encrypted text NOT NULL DEFAULT '',
    enabled boolean NOT NULL DEFAULT true,
    sort_order bigint NOT NULL DEFAULT 0,
    created_at text NOT NULL DEFAULT sakms_now(),
    updated_at text NOT NULL DEFAULT sakms_now()
);

CREATE TABLE settings (
    key text PRIMARY KEY,
    value text NOT NULL
);

CREATE TABLE stashbox_databases (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL UNIQUE,
    endpoint text NOT NULL,
    api_key_encrypted text NOT NULL DEFAULT '',
    priority bigint NOT NULL DEFAULT 0,
    enabled boolean NOT NULL DEFAULT true,
    fansite_only boolean NOT NULL DEFAULT false,
    secret_ref text NOT NULL DEFAULT '',
    created_at text NOT NULL DEFAULT sakms_now(),
    updated_at text NOT NULL DEFAULT sakms_now()
);

CREATE TABLE trakt_connection (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id text NOT NULL DEFAULT '',
    client_secret_encrypted text NOT NULL DEFAULT '',
    access_token_encrypted text NOT NULL DEFAULT '',
    refresh_token_encrypted text NOT NULL DEFAULT '',
    token_expires_at text NOT NULL DEFAULT '',
    created_at text NOT NULL DEFAULT sakms_now(),
    updated_at text NOT NULL DEFAULT sakms_now()
);

CREATE TABLE vmaf_scores (
    candidate_path text,
    candidate_file_size bigint NOT NULL DEFAULT 0,
    candidate_file_mtime text NOT NULL DEFAULT '',
    reference_path text,
    score double precision NOT NULL,
    computed_at text NOT NULL,
    PRIMARY KEY (candidate_path, reference_path)
);

CREATE TABLE webhooks (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url text NOT NULL,
    secret_enc text NOT NULL DEFAULT '',
    events text NOT NULL DEFAULT '[]',
    enabled boolean NOT NULL DEFAULT true,
    created_at text NOT NULL DEFAULT sakms_now_sec(),
    updated_at text NOT NULL DEFAULT sakms_now_sec()
);

CREATE TABLE library_episodes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    series_id bigint NOT NULL,
    season_number bigint NOT NULL,
    episode_number bigint NOT NULL,
    title text NOT NULL DEFAULT '',
    air_date text NOT NULL DEFAULT '',
    file_path text NOT NULL DEFAULT '',
    created_at text NOT NULL DEFAULT sakms_now(),
    updated_at text NOT NULL DEFAULT sakms_now(),
    phash text NOT NULL DEFAULT '',
    phash_file_size bigint NOT NULL DEFAULT 0,
    phash_file_mtime text NOT NULL DEFAULT '',
    size bigint NOT NULL DEFAULT 0,
    quality_tier text NOT NULL DEFAULT '',
    FOREIGN KEY (series_id) REFERENCES library_series (id) ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE,
    UNIQUE (series_id, season_number, episode_number)
);

CREATE TABLE library_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mode text NOT NULL,
    tmdb_id bigint NOT NULL,
    title text NOT NULL,
    year bigint NOT NULL DEFAULT 0,
    file_path text NOT NULL DEFAULT '',
    root_folder_path text NOT NULL,
    created_at text NOT NULL DEFAULT sakms_now(),
    updated_at text NOT NULL DEFAULT sakms_now(),
    phash text NOT NULL DEFAULT '',
    phash_file_size bigint NOT NULL DEFAULT 0,
    phash_file_mtime text NOT NULL DEFAULT '',
    collection_id bigint,
    genres text NOT NULL DEFAULT '[]',
    "cast" text NOT NULL DEFAULT '[]',
    size bigint NOT NULL DEFAULT 0,
    quality_tier text NOT NULL DEFAULT '',
    FOREIGN KEY (collection_id) REFERENCES library_collections (id) ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE,
    UNIQUE (mode, tmdb_id)
);

CREATE TABLE library_scene_tags (
    scene_id bigint,
    tag text,
    PRIMARY KEY (scene_id, tag),
    FOREIGN KEY (scene_id) REFERENCES library_scenes (id) ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE
);

CREATE TABLE library_series_tags (
    series_id bigint,
    tag text,
    PRIMARY KEY (series_id, tag),
    FOREIGN KEY (series_id) REFERENCES library_series (id) ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE
);

CREATE TABLE parse_performer_aliases (
    alias_norm text PRIMARY KEY,
    performer_id bigint NOT NULL,
    FOREIGN KEY (performer_id) REFERENCES parse_performers (id) ON DELETE CASCADE ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE
);

CREATE TABLE parse_studio_aliases (
    alias_norm text PRIMARY KEY,
    studio_id bigint NOT NULL,
    FOREIGN KEY (studio_id) REFERENCES parse_studios (id) ON DELETE CASCADE ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE
);

CREATE TABLE service_connection_modes (
    connection_id bigint,
    mode text,
    PRIMARY KEY (connection_id, mode),
    FOREIGN KEY (connection_id) REFERENCES service_connections (id) ON DELETE CASCADE ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE
);

CREATE TABLE library_tags (
    item_id bigint,
    tag text,
    PRIMARY KEY (item_id, tag),
    FOREIGN KEY (item_id) REFERENCES library_items (id) ON DELETE CASCADE ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE
);

CREATE INDEX idx_adult_newest_releases_row_type ON adult_newest_releases (row_type);

CREATE INDEX idx_adult_newest_rows_sort_order ON adult_newest_rows (sort_order);

-- Claude 2026-08-04: seed defaults previously in SQLite 0024 (+0048 titles).
-- Reason: fresh baseline has no numbered migration chain to insert them.
-- Troubleshooting: adultnewest tests expect 4 rows; empty table on new install.
-- Review if: default Discover row titles/types change.
INSERT INTO adult_newest_rows (title, row_type, sort_order) VALUES
    ('Newest Movies', 'movie', 0),
    ('Newest Scenes', 'scene', 1),
    ('New Performers', 'performer', 2),
    ('New Studios', 'studio', 3);

-- Claude 2026-08-04: seed stashbox_databases from archived SQLite 0061.
-- Reason: identify cascade defaults for new installs / tests.
-- Troubleshooting: empty stashbox_databases breaks adult identify tests.
-- Review if: default stashbox endpoints or secret_ref names change.
INSERT INTO stashbox_databases (name, endpoint, priority, enabled, fansite_only, secret_ref) VALUES
  ('stashdb', 'https://stashdb.org/graphql', 0, true, false, 'stashdb'),
  ('fansdb',  'https://fansdb.cc/graphql',   1, true, true, 'fansdb');

CREATE INDEX idx_availability_watch_last_checked ON availability_watch (last_checked_at);

CREATE INDEX idx_discover_sliders_sort_order ON discover_sliders (sort_order);

CREATE INDEX idx_grabs_download_gid ON grabs (download_gid);

CREATE UNIQUE INDEX idx_grabs_held_request ON grabs (mode, tmdb_id) WHERE hold_until != '';

CREATE INDEX idx_grabs_mode_status ON grabs (mode, status);

CREATE INDEX idx_library_episodes_series ON library_episodes (series_id);

CREATE INDEX idx_library_items_collection_id ON library_items(collection_id);

CREATE INDEX idx_library_items_mode ON library_items (mode);

CREATE INDEX idx_library_scenes_box_scene ON library_scenes (box, scene_id);

CREATE INDEX idx_library_series_tmdb ON library_series (tmdb_id);

CREATE INDEX idx_proposals_mode_workflow_status ON proposals (mode, workflow, status);

CREATE INDEX idx_pruning_rules_mode ON pruning_rules (mode, enabled);

CREATE UNIQUE INDEX idx_purge_allowlist_mode_tag ON purge_allowlist (mode, lower(tag));

CREATE INDEX idx_rss_feeds_sort_order ON rss_feeds (sort_order);

CREATE INDEX idx_service_connections_kind ON service_connections (kind, enabled);

CREATE INDEX idx_stashbox_databases_priority ON stashbox_databases (enabled, priority);

CREATE UNIQUE INDEX parse_performers_norm ON parse_performers (name_norm);

CREATE UNIQUE INDEX parse_studios_norm ON parse_studios (name_norm);

CREATE UNIQUE INDEX IF NOT EXISTS library_tags_tag_lower_uidx ON library_tags (item_id, lower(tag));

CREATE UNIQUE INDEX IF NOT EXISTS library_series_tags_tag_lower_uidx ON library_series_tags (series_id, lower(tag));

CREATE UNIQUE INDEX IF NOT EXISTS library_scene_tags_tag_lower_uidx ON library_scene_tags (scene_id, lower(tag));

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS library_tags CASCADE;
DROP TABLE IF EXISTS service_connection_modes CASCADE;
DROP TABLE IF EXISTS parse_studio_aliases CASCADE;
DROP TABLE IF EXISTS parse_performer_aliases CASCADE;
DROP TABLE IF EXISTS library_series_tags CASCADE;
DROP TABLE IF EXISTS library_scene_tags CASCADE;
DROP TABLE IF EXISTS library_items CASCADE;
DROP TABLE IF EXISTS library_episodes CASCADE;
DROP TABLE IF EXISTS webhooks CASCADE;
DROP TABLE IF EXISTS vmaf_scores CASCADE;
DROP TABLE IF EXISTS trakt_connection CASCADE;
DROP TABLE IF EXISTS stashbox_databases CASCADE;
DROP TABLE IF EXISTS settings CASCADE;
DROP TABLE IF EXISTS service_connections CASCADE;
DROP TABLE IF EXISTS rss_feeds CASCADE;
DROP TABLE IF EXISTS purge_allowlist CASCADE;
DROP TABLE IF EXISTS pruning_rules CASCADE;
DROP TABLE IF EXISTS proposals CASCADE;
DROP TABLE IF EXISTS parse_studios CASCADE;
DROP TABLE IF EXISTS parse_performers CASCADE;
DROP TABLE IF EXISTS parse_entity_sync CASCADE;
DROP TABLE IF EXISTS orphan_phashes CASCADE;
DROP TABLE IF EXISTS node_path_mappings CASCADE;
DROP TABLE IF EXISTS node_max_jobs CASCADE;
DROP TABLE IF EXISTS node_keys CASCADE;
DROP TABLE IF EXISTS library_series CASCADE;
DROP TABLE IF EXISTS library_season_monitored CASCADE;
DROP TABLE IF EXISTS library_scenes CASCADE;
DROP TABLE IF EXISTS library_collections CASCADE;
DROP TABLE IF EXISTS grabs CASCADE;
DROP TABLE IF EXISTS excluded_titles CASCADE;
DROP TABLE IF EXISTS discover_sliders CASCADE;
DROP TABLE IF EXISTS discover_row_cache CASCADE;
DROP TABLE IF EXISTS connections CASCADE;
DROP TABLE IF EXISTS availability_watch CASCADE;
DROP TABLE IF EXISTS adult_newest_seen CASCADE;
DROP TABLE IF EXISTS adult_newest_scene_matches CASCADE;
DROP TABLE IF EXISTS adult_newest_rows CASCADE;
DROP TABLE IF EXISTS adult_newest_releases CASCADE;
DROP FUNCTION IF EXISTS sakms_now();
DROP FUNCTION IF EXISTS sakms_now_sec();
-- +goose StatementEnd
