-- +goose Up
-- Claude 2026-08-05: organize_events — operational activity log for Rename/Dedup/Purge
-- Reason: deep-interview-organize-pagination-log — persistent scan/apply/dismiss/error stream
-- Troubleshooting: prune at 30 days AND 5000 rows global (whichever binds first)
-- Review if: retention defaults become Settings-tunable

CREATE TABLE organize_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workflow text NOT NULL,
    mode text NOT NULL DEFAULT '',
    kind text NOT NULL,
    proposal_id bigint NOT NULL DEFAULT 0,
    ok boolean,
    message text NOT NULL DEFAULT '',
    detail_json text NOT NULL DEFAULT '',
    created_at text NOT NULL DEFAULT sakms_now()
);

CREATE INDEX organize_events_created_at_idx ON organize_events (created_at);
CREATE INDEX organize_events_workflow_created_at_idx ON organize_events (workflow, created_at DESC);

-- +goose Down
DROP INDEX IF EXISTS organize_events_workflow_created_at_idx;
DROP INDEX IF EXISTS organize_events_created_at_idx;
DROP TABLE IF EXISTS organize_events;
