-- +goose Up
-- Claude 2026-08-05: library_item_files — multi-file (primary + alternates) per movie title
-- Reason: deep-interview-rename-alts-ai-fallback — Rename folds duplicates under one TMDB id
-- Troubleshooting: UNIQUE(mode,tmdb_id) on library_items kept; file_path there = denormalized primary
-- Review if: Series gains multi-file or primary moves off library_items.file_path

CREATE TABLE library_item_files (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id bigint NOT NULL,
    file_path text NOT NULL,
    is_primary boolean NOT NULL DEFAULT false,
    quality_tier text NOT NULL DEFAULT '',
    size bigint NOT NULL DEFAULT 0,
    width integer NOT NULL DEFAULT 0,
    height integer NOT NULL DEFAULT 0,
    video_codec text NOT NULL DEFAULT '',
    bitrate bigint NOT NULL DEFAULT 0,
    duration_sec double precision NOT NULL DEFAULT 0,
    phash text NOT NULL DEFAULT '',
    created_at text NOT NULL DEFAULT sakms_now(),
    updated_at text NOT NULL DEFAULT sakms_now(),
    FOREIGN KEY (item_id) REFERENCES library_items (id) ON DELETE CASCADE ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE,
    UNIQUE (file_path)
);

CREATE UNIQUE INDEX library_item_files_one_primary
    ON library_item_files (item_id)
    WHERE is_primary;

CREATE INDEX library_item_files_item_id ON library_item_files (item_id);

-- Backfill one primary file row per existing movie item that has a path.
INSERT INTO library_item_files (
    item_id, file_path, is_primary, quality_tier, size, phash
)
SELECT id, file_path, true, quality_tier, size, phash
FROM library_items
WHERE file_path <> '';

-- +goose Down
DROP INDEX IF EXISTS library_item_files_item_id;
DROP INDEX IF EXISTS library_item_files_one_primary;
DROP TABLE IF EXISTS library_item_files;
