-- +goose Up
-- Claude 2026-08-07: library_episode_files — multi-file (primary + alternates) per episode slot
-- Reason: deep-interview-sakms-series-parsing-accuracy-improvements — Series gains Movies-parity
--   alternate-version support; mirrors library_item_files (migration 0003) for episodes.
-- Troubleshooting: UNIQUE(series_id, season_number, episode_number) on library_episodes is kept;
--   library_episodes.file_path stays the DENORMALIZED PRIMARY, exactly as library_items.file_path is.
-- Review if: library_episodes.file_path stops being the denormalized primary, or Purge/Dedup gain
--   alternate awareness (see .omc/plans/autopilot-impl.md §11).

CREATE TABLE library_episode_files (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    episode_id bigint NOT NULL,
    file_path text NOT NULL,
    is_primary boolean NOT NULL DEFAULT false,
    quality_tier text NOT NULL DEFAULT '',
    size bigint NOT NULL DEFAULT 0,
    width integer NOT NULL DEFAULT 0,
    height integer NOT NULL DEFAULT 0,
    video_codec text NOT NULL DEFAULT '',
    bitrate bigint NOT NULL DEFAULT 0,
    duration_sec double precision NOT NULL DEFAULT 0,
    phash text NOT NULL DEFAULT '',
    created_at text NOT NULL DEFAULT sakms_now(),
    updated_at text NOT NULL DEFAULT sakms_now(),
    FOREIGN KEY (episode_id) REFERENCES library_episodes (id) ON DELETE CASCADE ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE,
    -- NOT UNIQUE(file_path), unlike library_item_files. A logical-episode-split file
    -- (rename.RelocateEpisodeRange) legitimately backs SEVERAL library_episodes rows at one
    -- path, so a bare UNIQUE(file_path) would make the backfill below fail outright.
    UNIQUE (episode_id, file_path)
);

CREATE UNIQUE INDEX library_episode_files_one_primary
    ON library_episode_files (episode_id)
    WHERE is_primary;

CREATE INDEX library_episode_files_episode_id ON library_episode_files (episode_id);

-- Backfill one primary file row per existing episode that has a path. A range file's
-- N episode rows produce N primary rows (one per episode_id, same path) — deliberate:
-- each episode slot owns exactly one primary, which is what the partial index enforces.
INSERT INTO library_episode_files (
    episode_id, file_path, is_primary, quality_tier, size, phash
)
SELECT id, file_path, true, quality_tier, size, phash
FROM library_episodes
WHERE file_path <> '';

-- +goose Down
-- SCHEMA-REVERSIBLE, NOT OPERATIONALLY REVERSIBLE (.omc/plans/autopilot-impl.md §2.2).
-- The statements below are correct and safe *as schema*. That is the narrow claim.
-- Once an Apply has folded an alternate, this feature is NOT undoable by rolling back:
--   * the demoted file has already been PHYSICALLY RENAMED on disk by moveUnique, carrying
--     an EpisodeAlternateFileName suffix (" - 1080p h264 …" / " - alternate");
--   * library_episodes.file_path has already been rewritten by UpdateEpisodePrimaryPath on
--     every promotion.
-- Dropping this table discards the only record tying a demoted file to its episode slot. The
-- file is not deleted (nothing in this feature ever deletes a file) — it becomes an untracked
-- orphan under a mangled name that the next Scan re-proposes as a fresh duplicate. That is
-- operational churn, not data loss, and the Down block cannot undo it.
-- SAFE ROLLBACK PATH: leave 0005 applied and revert the application binary only — an old
-- binary against a 0005 database is a clean no-op (goose's dbMaxVersion gate). Never hand-delete
-- the 0005 row from goose_db_version without dropping the table: goose.Up is called with no
-- allowMissing option, so a gap below dbMaxVersion is a hard startup error.
-- Index drops precede the table drop, matching 0003's ordering.
DROP INDEX IF EXISTS library_episode_files_episode_id;
DROP INDEX IF EXISTS library_episode_files_one_primary;
DROP TABLE IF EXISTS library_episode_files;
