-- +goose Up
-- Claude 2026-08-09: rename_undo_archive — per-mode rolling N-deep Rename undo
-- Reason: deep-interview-rename-undo — nothing today records a file's pre-Apply state
--   once Apply has run (every Apply persists only the DESTINATION path), so reversing a
--   completed Apply is impossible without new schema. One row per undoable Apply.
-- Troubleshooting: "nothing to undo for this proposal" (404) on a freshly-Applied item →
--   either rename.SetDefaultUndoStore was never called at boot (archiving silently no-ops
--   when unset, by design — see recordUndoArchive) or the entry was evicted by the mode's
--   configured undo depth.
-- Review if: Delete or Dismiss ever gain undo (both are explicitly out of scope today), or
--   library_item_files/library_episode_files become reversible (they deliberately are not —
--   see undo_apply.go's revertTouchedRows doc comment).

CREATE TABLE rename_undo_archive (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proposal_id bigint NOT NULL,
    mode text NOT NULL,
    applied_at text NOT NULL,
    -- Everything needed to move the file(s) back and restore proposal state.
    pre_apply_source_path text NOT NULL,
    pre_apply_proposal_snapshot text NOT NULL,   -- JSON: full pre-Apply Proposal row
    -- Everything the Apply's write touched. For a simple Apply this is one
    -- entry; a Series range Apply writes one entry per bundled episode. See
    -- rename.touchedRow for the exact JSON shape.
    --
    -- DELIBERATELY INCOMPLETE FOR TWO SHARED ROWS, and that is not a bug:
    --   * library_series (UNIQUE(tmdb_id), shared by every episode of a show)
    --   * library_items keyed (mode='movies', tmdb_id=0) (shared by every
    --     unidentified-movie Apply)
    -- Both are excluded at CAPTURE time and must never be "filled in" at undo
    -- time — reverting either would clobber a sibling proposal's later, still
    -- valid Apply. See the spec's Constraints and the plan's §3/§6-step-3.
    touched_rows_snapshot text NOT NULL,          -- JSON array
    -- DEVIATION FROM THE PLAN'S COLUMN LIST, and it is load-bearing: the plan
    -- specified no post-Apply path/size anywhere, but the undo file-move gate
    -- is a SIZE MATCH against the file the Apply actually left on disk. Nothing
    -- else in this row can supply it — touched_rows_snapshot holds PRE-Apply
    -- paths/sizes, is null-shaped for an INSERT, and is legitimately EMPTY for
    -- the two shared-row exclusions above (a zero-TMDBID Movies Apply still has
    -- a real file to move back). So the gate's inputs live at archive level.
    -- post_apply_size = 0 means "the stat failed at Apply time"; a real file
    -- then mismatches and the move is skipped, which is the safe direction.
    post_apply_path text NOT NULL DEFAULT '',
    post_apply_size bigint NOT NULL DEFAULT 0,
    via_alternate_fold boolean NOT NULL DEFAULT false,
    -- DEVIATION (Adult only): ApplyLibraryAdult's fingerprintSubmitted is a
    -- return value persisted onto the PROPOSAL, and the proposal snapshot here
    -- is the PRE-Apply row, where it is empty by definition. Reading the live
    -- proposal at undo time cannot distinguish "this Apply submitted" from "a
    -- later manual retry submitted", so the fact is captured here instead.
    give_back_submitted boolean NOT NULL DEFAULT false,
    -- Two SEPARATE lifecycle fields, not one. consumed_at = this entry was
    -- undone (terminal — an undone entry is never undoable again). evicted_at
    -- = the per-mode N-depth eviction pushed it out. Undoing an entry must
    -- NOT clear/backdate evicted_at, and eviction must never touch
    -- consumed_at. Collapsing these into one column means undoing an entry
    -- silently frees an eviction slot and the undo-window quietly grows back
    -- past the configured N — confirmed as a real bug risk during planning,
    -- not a hypothetical.
    --
    -- Eviction is a SOFT delete (evicted_at = sakms_now()) rather than the hard
    -- DELETE organizeevents.Prune uses. Deliberate divergence: a hard delete
    -- makes evicted_at unnecessary, which collapses the two lifecycle fields
    -- into one by the back door — exactly what the paragraph above forbids —
    -- and makes "only the most recent N rows are still active" unobservable.
    consumed_at text,                              -- set when undone
    evicted_at text,                               -- set when N-depth eviction prunes it
    created_at text NOT NULL DEFAULT sakms_now()
);

CREATE INDEX idx_rename_undo_archive_mode_proposal ON rename_undo_archive (mode, proposal_id);
-- Supports "N most recent undoable entries per mode" (consumed_at IS NULL AND
-- evicted_at IS NULL) and eviction queries (evicted_at IS NULL, ordered by
-- created_at) against both lifecycle fields independently.
CREATE INDEX idx_rename_undo_archive_mode_active ON rename_undo_archive (mode, consumed_at, evicted_at, created_at);

-- +goose Down
-- SCHEMA-REVERSIBLE, NOT OPERATIONALLY REVERSIBLE — same caveat 0005 documents.
-- The statements below are correct and safe *as schema*. That is the narrow claim.
-- Dropping this table discards the ONLY record of any Apply's pre-Apply state: the
-- pre-Apply source path, the pre-Apply library row snapshots, and the pre-Apply
-- proposal rows. Nothing else in the schema carries them, so every still-undoable
-- Apply becomes permanently un-undoable the moment this runs. No file is moved and
-- no library row is changed (this table is write-then-read-only; nothing else joins
-- to it), so this is capability loss, not data corruption — but it cannot be undone
-- by re-running the Up block.
-- SAFE ROLLBACK PATH: leave 0006 applied and revert the application binary only — an
-- old binary against a 0006 database is a clean no-op (goose's dbMaxVersion gate).
-- Never hand-delete the 0006 row from goose_db_version without dropping the table:
-- goose.Up is called with no allowMissing option, so a gap below dbMaxVersion is a
-- hard startup error.
-- Index drops precede the table drop, matching 0003/0005's ordering.
DROP INDEX IF EXISTS idx_rename_undo_archive_mode_active;
DROP INDEX IF EXISTS idx_rename_undo_archive_mode_proposal;
DROP TABLE IF EXISTS rename_undo_archive;
