-- +goose Up
-- Claude 2026-08-11: add pruning_rules.tags; migrate purge_allowlist into
--   auto-created per-mode rules; drop purge_allowlist.
-- Reason: deep-interview-purge-rules-consolidation-cleanup-rename — tags become
--   a genuine 4th AND'd per-rule condition (internal/pruning), retiring the
--   global per-mode allowlist mechanism entirely. Existing operator-configured
--   tags must keep matching, so they are converted, not discarded.
-- Troubleshooting: `tags` is JSON-encoded TEXT, not text[] — same convention as
--   library_items.genres/"cast" (internal/library/library.go marshalStringSlice).
--   to_jsonb(array_agg(...)) is used rather than json_agg so the encoding is
--   compact and stable; Go's json.Unmarshal accepts either.
-- Review if: pruning rules ever gain a fifth condition, or tags move to a join
--   table.
ALTER TABLE pruning_rules ADD COLUMN tags text NOT NULL DEFAULT '[]';

-- One rule per mode that actually HAS tags. A mode with an empty allowlist gets
-- NO rule: an empty-tags rule would be conditionless, would fail Validate on the
-- next edit, and would clutter the new Rules card with a row that matches
-- nothing.
INSERT INTO pruning_rules (name, mode, age_days, size_bytes, quality_tier_floor, tags, enabled)
SELECT 'Legacy allowlist',
       mode,
       0, 0, '',
       to_jsonb(array_agg(tag ORDER BY lower(tag)))::text,
       true
FROM purge_allowlist
-- btrim guard: pruning.ErrBlankTag is STRICTER than the retired
-- addAllowlistTagHandler guard it replaces (that one rejected only exactly "",
-- never whitespace-only), so a pre-existing " " row in live data would migrate
-- into a rule that fails validation on the operator's next edit. Same class of
-- guard as the zero-tags case above, for the same reason.
WHERE btrim(tag) <> ''
GROUP BY mode;

-- Dropping the table drops idx_purge_allowlist_mode_tag with it (Postgres);
-- an explicit DROP INDEX first is unnecessary, not merely redundant.
DROP TABLE purge_allowlist;

-- +goose Down
-- Best-effort, and deliberately NOT a no-op: unlike 0007 (which only deleted
-- rows), this Up drops a table, so a no-op Down would leave a schema no code
-- can run against.
--
-- KNOWN, ACCEPTED LOSSINESS: a rule combining tags WITH age/size/tier keeps its
-- other conditions but LOSES its tags on rollback, because purge_allowlist has
-- nowhere to put a tag that is only meaningful alongside another condition.
-- That is unavoidable, and it is why the delete below removes only TAG-ONLY
-- rows.
CREATE TABLE purge_allowlist (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mode text NOT NULL,
    tag text NOT NULL,
    created_at text NOT NULL DEFAULT sakms_now()
);
CREATE UNIQUE INDEX idx_purge_allowlist_mode_tag ON purge_allowlist (mode, lower(tag));

-- Restore tags from TAG-ONLY rules — a STRUCTURAL discriminator (all three other
-- conditions unset), never a name match on 'Legacy allowlist'. Inferring a row's
-- origin from a string is the exact anti-pattern CLAUDE.md records under
-- grabs.hold_until, where it destroyed an operator's own grab.
INSERT INTO purge_allowlist (mode, tag)
SELECT r.mode, t.value
FROM pruning_rules r,
     LATERAL jsonb_array_elements_text(r.tags::jsonb) AS t(value)
WHERE r.age_days = 0 AND r.size_bytes = 0 AND r.quality_tier_floor = ''
ON CONFLICT DO NOTHING;

DELETE FROM pruning_rules
WHERE age_days = 0 AND size_bytes = 0 AND quality_tier_floor = ''
  AND tags <> '[]';

ALTER TABLE pruning_rules DROP COLUMN tags;
