-- +goose Up
-- Claude 2026-08-12: library_scene_files — multi-file (primary + alternates) per Adult scene
-- Reason: deep-interview-adult-rename-review-alts — Adult gains the Movies/Series
--   alternate-version scheme; mirrors library_item_files (0003) and
--   library_episode_files (0005).
-- Troubleshooting: UNIQUE(box, scene_id) on library_scenes is KEPT;
--   library_scenes.file_path stays the DENORMALIZED PRIMARY, exactly as
--   library_items.file_path and library_episodes.file_path are.
-- NAME HAZARD: this table's `scene_id` is library_scenes.id (a bigint row id),
--   NOT library_scenes.scene_id (the text stash-box id). Matches
--   library_scene_tags.scene_id. ALWAYS alias both tables in any join.
-- Review if: library_scenes.file_path stops being the denormalized primary, or
--   Dedup/Purge gain alternate awareness.

CREATE TABLE library_scene_files (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scene_id bigint NOT NULL,
    file_path text NOT NULL,
    is_primary boolean NOT NULL DEFAULT false,
    quality_tier text NOT NULL DEFAULT '',
    size bigint NOT NULL DEFAULT 0,
    width integer NOT NULL DEFAULT 0,
    height integer NOT NULL DEFAULT 0,
    video_codec text NOT NULL DEFAULT '',
    bitrate bigint NOT NULL DEFAULT 0,
    duration_sec double precision NOT NULL DEFAULT 0,
    phash text NOT NULL DEFAULT '',
    created_at text NOT NULL DEFAULT sakms_now(),
    updated_at text NOT NULL DEFAULT sakms_now(),
    FOREIGN KEY (scene_id) REFERENCES library_scenes (id) ON DELETE CASCADE ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE,
    -- UNIQUE(file_path), matching library_item_files and NOT library_episode_files.
    -- The episode variant needs the wider (episode_id, file_path) key only because a
    -- range file legitimately backs several episode rows. An Adult scene is a flat
    -- one-file thing with no range concept, so one path belongs to exactly one scene
    -- and the narrow key is both correct and stronger.
    UNIQUE (file_path)
);

CREATE UNIQUE INDEX library_scene_files_one_primary
    ON library_scene_files (scene_id)
    WHERE is_primary;

CREATE INDEX library_scene_files_scene_id ON library_scene_files (scene_id);

-- Backfill one primary file row per existing scene that has a path.
-- Pre-flight: SELECT file_path, COUNT(*) FROM library_scenes
--   WHERE file_path <> '' GROUP BY file_path HAVING COUNT(*) > 1
-- must return zero rows before running this migration. If it returns rows,
-- switch the UNIQUE constraint above to UNIQUE (scene_id, file_path) and
-- adjust UpsertSceneFile's ON CONFLICT target to match.
INSERT INTO library_scene_files (scene_id, file_path, is_primary, quality_tier, size, phash)
SELECT id, file_path, true, quality_tier, size, phash
FROM library_scenes
WHERE file_path <> '';

-- +goose Down
-- SCHEMA-REVERSIBLE, NOT OPERATIONALLY REVERSIBLE — identical reasoning to 0005's
-- Down block. Once an Apply has folded an Adult alternate:
--   * the demoted file has already been PHYSICALLY RENAMED on disk by moveUnique,
--     carrying an AdultAlternateFileName suffix;
--   * library_scenes.file_path has already been rewritten by UpdateScenePrimaryPath
--     on every promotion, along with its phash cache key.
-- Dropping this table discards the only record tying a demoted file to its scene. The
-- file is not deleted — it becomes an untracked orphan the next Scan re-proposes.
-- SAFE ROLLBACK PATH: leave 0010 applied and revert the application binary only.
-- Never hand-delete the 0010 row from goose_db_version without dropping the table.
--
-- Note: rolling back 0010 leaves local library_scenes rows (box='local') in place.
-- They are ordinary rows with box='local', and an old binary reads them as tracked
-- scenes it does not understand but does not corrupt.
DROP INDEX IF EXISTS library_scene_files_scene_id;
DROP INDEX IF EXISTS library_scene_files_one_primary;
DROP TABLE IF EXISTS library_scene_files;
