#!/usr/bin/env python3
"""Generate Postgres goose baseline from a live SQLite sakms.db (read-only)."""
from __future__ import annotations

import re
import sqlite3
import sys

SKIP = {"sqlite_sequence", "goose_db_version"}
TAG_PK_TABLES = {
    "library_tags": ("item_id", "tag"),
    "library_series_tags": ("series_id", "tag"),
    "library_scene_tags": ("scene_id", "tag"),
}


def map_type(decl: str | None, col: str = "") -> str:
    d = (decl or "TEXT").upper()
    # Claude 2026-08-04: Go binds these as bool; PG rejects bool→bigint.
    if col.lower() in {
        "enabled",
        "fansite_only",
        "browse_confirmed",
        "season_specified",
        "flagged_for_review",
        "pause_dispatch",
        "monitored",
        "tls",
    }:
        return "boolean"
    if "INT" in d:
        return "bigint"
    if "REAL" in d or "FLOA" in d or "DOUB" in d:
        return "double precision"
    return "text"


def convert_default(default: str | None) -> str | None:
    if default is None:
        return None
    d = default.strip()
    if d.startswith("(") and d.endswith(")"):
        d = d[1:-1].strip()
    compact = d.replace(" ", "")
    if "strftime('%Y-%m-%dT%H:%M:%fZ'" in compact or ("%fZ" in d and "strftime" in d):
        return "sakms_now()"
    if "strftime('%Y-%m-%dT%H:%M:%SZ'" in compact or ("%SZ" in d and "strftime" in d and "%f" not in d):
        return "sakms_now_sec()"
    return d


def qident(name: str) -> str:
    if name.lower() == "cast" or not name.replace("_", "").isalnum():
        return f'"{name}"'
    return name


def main() -> int:
    db_path = sys.argv[1] if len(sys.argv) > 1 else "/mnt/iscsi/sakms/sakms.db"
    out = sys.argv[2] if len(sys.argv) > 2 else "-"
    c = sqlite3.connect(f"file:{db_path}?mode=ro", uri=True)
    c.row_factory = sqlite3.Row

    tables = [
        r[0]
        for r in c.execute(
            "SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name"
        )
        if r[0] not in SKIP
    ]

    fks_by_table: dict[str, list] = {}
    for t in tables:
        rows = list(c.execute(f"PRAGMA foreign_key_list({t})"))
        if rows:
            fks_by_table[t] = rows

    # Claude 2026-08-04: FK-aware create order (SQLite ORDER BY name broke PG).
    # Reason: Postgres enforces REFERENCES at CREATE; alpha sort put episodes before series.
    # Troubleshooting: ERROR relation "…" does not exist during goose Up.
    # Review if: schema gains cyclic FKs (then split FK into ALTER TABLE).
    def topo_tables(names: list[str]) -> list[str]:
        deps: dict[str, set[str]] = {n: set() for n in names}
        for t, fks in fks_by_table.items():
            for fk in fks:
                parent = fk[2]
                if parent in deps and parent != t:
                    deps[t].add(parent)
        remaining = set(names)
        ordered: list[str] = []
        while remaining:
            ready = sorted(n for n in remaining if not (deps[n] & remaining))
            if not ready:
                # Cycle: fall back to alpha among remaining (DEFERRABLE alone won't help CREATE)
                ordered.extend(sorted(remaining))
                break
            for n in ready:
                ordered.append(n)
                remaining.remove(n)
        return ordered

    tables = topo_tables(tables)

    lines_out: list[str] = []
    w = lines_out.append

    w("-- +goose Up")
    w("-- Claude 2026-08-04: fresh Postgres baseline (SQLite chain archived).")
    w("-- Reason: Postgres-only migration; deep-interview-sakms-postgres-migration.")
    w("-- Troubleshooting: ETL needs GENERATED BY DEFAULT AS IDENTITY for explicit ids.")
    w("-- Review if: live schema drifts; regenerate from sakms.db and re-diff.")
    w("")
    w("-- +goose StatementBegin")
    w("CREATE OR REPLACE FUNCTION sakms_now() RETURNS text LANGUAGE sql VOLATILE AS $$")
    w("  SELECT to_char(clock_timestamp() AT TIME ZONE 'utc', 'YYYY-MM-DD\"T\"HH24:MI:SS.MS\"Z\"')")
    w("$$;")
    w("CREATE OR REPLACE FUNCTION sakms_now_sec() RETURNS text LANGUAGE sql VOLATILE AS $$")
    w("  SELECT to_char(clock_timestamp() AT TIME ZONE 'utc', 'YYYY-MM-DD\"T\"HH24:MI:SS\"Z\"')")
    w("$$;")
    w("-- +goose StatementEnd")
    w("")

    for t in tables:
        cols = list(c.execute(f"PRAGMA table_info({t})"))
        pk_cols = [col[1] for col in sorted(cols, key=lambda x: x[5]) if col[5] > 0]
        sql_row = c.execute(
            "SELECT sql FROM sqlite_master WHERE type='table' AND name=?", (t,)
        ).fetchone()
        create_sql = (sql_row[0] or "") if sql_row else ""
        auto = "AUTOINCREMENT" in create_sql.upper()
        if not auto and len(pk_cols) == 1:
            pkcol = next(col for col in cols if col[1] == pk_cols[0])
            if "INT" in (pkcol[2] or "").upper() and re.search(
                r"INTEGER\s+PRIMARY\s+KEY", create_sql, re.I
            ):
                auto = True

        col_lines: list[str] = []
        for col in cols:
            _cid, name, ctype, notnull, dflt, pk = col
            qn = qident(name)
            parts: list[str]
            if auto and pk == 1 and len(pk_cols) == 1 and name == pk_cols[0]:
                parts = [qn, "bigint GENERATED BY DEFAULT AS IDENTITY"]
            else:
                parts = [qn, map_type(ctype, name)]
            if notnull and pk == 0:
                parts.append("NOT NULL")
            if pk and len(pk_cols) == 1:
                parts.append("PRIMARY KEY")
            d = convert_default(dflt)
            if d is not None and not (auto and pk):
                if d.startswith("sakms_"):
                    parts.append(f"DEFAULT {d}")
                else:
                    parts.append(f"DEFAULT {d}")
            col_lines.append("    " + " ".join(parts))

        extras: list[str] = []
        if len(pk_cols) > 1:
            extras.append(f"    PRIMARY KEY ({', '.join(qident(p) for p in pk_cols)})")

        if t in fks_by_table:
            by_id: dict[int, list] = {}
            for fk in fks_by_table[t]:
                by_id.setdefault(fk[0], []).append(fk)
            action_map = {
                "CASCADE": "CASCADE",
                "SET NULL": "SET NULL",
                "SET DEFAULT": "SET DEFAULT",
                "RESTRICT": "RESTRICT",
                "NO ACTION": "NO ACTION",
            }
            for _fid, parts_fk in by_id.items():
                parts_fk = sorted(parts_fk, key=lambda x: x[1])
                cols_from = [p[3] for p in parts_fk]
                cols_to = [p[4] for p in parts_fk]
                parent = parts_fk[0][2]
                od = action_map.get((parts_fk[0][6] or "NO ACTION").upper(), "NO ACTION")
                ou = action_map.get((parts_fk[0][5] or "NO ACTION").upper(), "NO ACTION")
                extras.append(
                    f"    FOREIGN KEY ({', '.join(cols_from)}) REFERENCES {parent} ({', '.join(cols_to)}) "
                    f"ON DELETE {od} ON UPDATE {ou} DEFERRABLE INITIALLY IMMEDIATE"
                )

        # Column-level UNIQUE (e.g. exclude_key TEXT NOT NULL UNIQUE) — not UNIQUE(...).
        for m in re.finditer(
            r"(?i)\b([a-z_][a-z0-9_]*)\s+(?:INTEGER|TEXT|REAL|BLOB|NUMERIC)(?:\s*\([^)]*\))?(?:\s+NOT\s+NULL)?\s+UNIQUE\b",
            create_sql,
        ):
            col = m.group(1)
            if col.lower() not in {p.lower() for p in pk_cols}:
                extras.append(f"    UNIQUE ({qident(col)})")

        # UNIQUE(...) from CREATE TABLE SQL (non-PK)
        for m in re.finditer(r"UNIQUE\s*\(([^)]+)\)", create_sql, re.I):
            extras.append(f"    UNIQUE ({m.group(1).strip()})")

        w(f"CREATE TABLE {t} (")
        w(",\n".join(col_lines + extras))
        w(");")
        w("")

    for name, tbl, sql in c.execute(
        "SELECT name, tbl_name, sql FROM sqlite_master WHERE type='index' AND sql IS NOT NULL ORDER BY name"
    ):
        if tbl in SKIP:
            continue
        s = re.sub(r"COLLATE\s+NOCASE", "", sql, flags=re.I)
        if re.search(r"\(\s*mode\s*,\s*tag\s*\)", s, re.I):
            s = re.sub(r"\(\s*mode\s*,\s*tag\s*\)", "(mode, lower(tag))", s, flags=re.I)
        w(s + ";")
        w("")

    for t, (idcol, tagcol) in TAG_PK_TABLES.items():
        w(f"CREATE UNIQUE INDEX IF NOT EXISTS {t}_{tagcol}_lower_uidx ON {t} ({idcol}, lower({tagcol}));")
        w("")

    # Seeds formerly in SQLite migrations 0024 / 0061 — required for empty installs + tests.
    w("-- Default Adult Discover rows (archived 0024 titles after 0048 rename)")
    w("INSERT INTO adult_newest_rows (title, row_type, sort_order) VALUES")
    w("    ('Newest Movies', 'movie', 0),")
    w("    ('Newest Scenes', 'scene', 1),")
    w("    ('New Performers', 'performer', 2),")
    w("    ('New Studios', 'studio', 3);")
    w("")
    w("-- Default stashbox cascade (archived 0061)")
    w("INSERT INTO stashbox_databases (name, endpoint, priority, enabled, fansite_only, secret_ref) VALUES")
    w("  ('stashdb', 'https://stashdb.org/graphql', 0, true, false, 'stashdb'),")
    w("  ('fansdb',  'https://fansdb.cc/graphql',   1, true, true, 'fansdb');")
    w("")

    w("-- +goose Down")
    w("-- +goose StatementBegin")
    for t in reversed(tables):
        w(f"DROP TABLE IF EXISTS {t} CASCADE;")
    w("DROP FUNCTION IF EXISTS sakms_now();")
    w("DROP FUNCTION IF EXISTS sakms_now_sec();")
    w("-- +goose StatementEnd")

    text = "\n".join(lines_out) + "\n"
    if out == "-":
        sys.stdout.write(text)
    else:
        with open(out, "w", encoding="utf-8") as f:
            f.write(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
